import { assertInventoryRemainsNonNegative, consumptionValueMinor, createInventoryMovement, createMaterial, summarizeMaterialInventory, type InventoryMovement, type Material, type MaterialUnit } from "@micro-domain/inventory-material/index.js";
import type { PrototypeLocalStore } from "@/storage/local/types";

export type InventoryResult<T> = { ok: true; value: T; reused?: boolean } | { ok: false; code: "validation_error" | "storage_error"; message: string };
export type InventoryMaterialOverview = Material & { quantityMilli: number; valueMinor: number; movementCount: number };
export type InventoryOverview = { materials: readonly InventoryMaterialOverview[]; movementCount: number; truth: string };
export type InventoryReferences = { materials: readonly Material[]; purchases: readonly { id: string; supplierName: string; note: string; totalMinor: number }[]; orders: readonly { id: string; itemName: string; customerName: string }[] };
export type OpenMaterialInput = { name: string; unit: MaterialUnit; openingQuantityMilli: number; openingValueMinor: number; occurredOn: string; note: string; operationKey: string };
export type ReceivePurchaseInput = { materialId: string; purchaseId: string; quantityMilli: number; valueMinor: number; occurredOn: string; note: string; operationKey: string };
export type ConsumeMaterialInput = { materialId: string; orderId: string; quantityMilli: number; occurredOn: string; note: string; operationKey: string };
export type WasteMaterialInput = { materialId: string; quantityMilli: number; occurredOn: string; note: string; reason: string; operationKey: string };
export type AdjustMaterialInput = { materialId: string; quantityDeltaMilli: number; valueMinorWhenIncrease: number | null; occurredOn: string; note: string; reason: string; operationKey: string };
export type ReverseInventoryInput = { movementId: string; occurredOn: string; reason: string; operationKey: string };

const id = (prefix: string) => globalThis.crypto?.randomUUID?.() ?? `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const storageFailure = <T>(): InventoryResult<T> => ({ ok: false, code: "storage_error", message: "تعذر حفظ حركة المادة محليًا. لم يتم تأكيد نجاح العملية." });

export class InventoryMaterialService {
  constructor(private readonly store: PrototypeLocalStore, private readonly now: () => string = () => new Date().toISOString()) {}
  async overview(): Promise<InventoryResult<InventoryOverview>> { const [materials, movements] = await Promise.all([this.store.listMaterials(), this.store.listInventoryMovements()]); if (!materials.ok || !movements.ok) return { ok: false, code: "storage_error", message: "تعذر قراءة المواد المحلية." }; return { ok: true, value: { materials: materials.value.map((material) => ({ ...material, ...summarizeMaterialInventory(material.id, movements.value) })), movementCount: movements.value.length, truth: "قيمة المادة المتاحة ليست مصروفًا أو تكلفة بيع. ينتقل الجزء المستهلك أو المهدر فقط إلى أثر واضح، ولا يغير هذا الإصدار Snapshot أو نتيجة فترة سابقة." } }; }
  async movements(): Promise<InventoryResult<readonly InventoryMovement[]>> { const result = await this.store.listInventoryMovements(); return result.ok ? { ok: true, value: result.value } : { ok: false, code: "storage_error", message: "تعذر قراءة حركات المواد المحلية." }; }
  async references(): Promise<InventoryResult<InventoryReferences>> { const [materials, purchases, orders] = await Promise.all([this.store.listMaterials(), this.store.listSupplierPurchases(), this.store.listOrders()]); if (!materials.ok || !purchases.ok || !orders.ok) return { ok: false, code: "storage_error", message: "تعذر قراءة مراجع المادة أو الشراء أو الطلب." }; return { ok: true, value: { materials: materials.value, purchases: purchases.value.map((purchase) => ({ id: purchase.id, supplierName: purchase.supplierName, note: purchase.note, totalMinor: purchase.totalMinor })), orders: orders.value.map((stored) => ({ id: stored.id, itemName: stored.order.itemName, customerName: stored.order.customerName })) } }; }
  async openMaterial(input: OpenMaterialInput): Promise<InventoryResult<{ material: Material; opening: InventoryMovement | null }>> { const [materials, movements] = await Promise.all([this.store.listMaterials(), this.store.listInventoryMovements()]); if (!materials.ok || !movements.ok) return storageFailure(); const repeated = materials.value.find((material) => material.createdOperationKey === input.operationKey); if (repeated) return { ok: true, value: { material: repeated, opening: movements.value.find((movement) => movement.operationKey === input.operationKey) ?? null }, reused: true }; try { const noOpening = input.openingQuantityMilli === 0 && input.openingValueMinor === 0; if (!noOpening && (input.openingQuantityMilli <= 0 || input.openingValueMinor <= 0)) throw new Error("رصيد المادة الافتتاحي يحتاج كمية وقيمة موجبتين، أو اتركهما صفرًا معًا."); const material = createMaterial({ id: id("material"), name: input.name, unit: input.unit, createdAt: this.now(), createdOperationKey: input.operationKey }); const opening = noOpening ? null : createInventoryMovement({ id: id("opening-material"), materialId: material.id, type: "opening", occurredOn: input.occurredOn, recordedAt: this.now(), quantityDeltaMilli: input.openingQuantityMilli, valueDeltaMinor: input.openingValueMinor, note: input.note, operationKey: input.operationKey }); const saved = await this.store.commitInventory(material, opening ? [opening] : []); return saved.ok ? { ok: true, value: { material, opening } } : storageFailure(); } catch (error) { return { ok: false, code: "validation_error", message: error instanceof Error ? error.message : "بيانات المادة غير صالحة." }; } }
  async receivePurchase(input: ReceivePurchaseInput): Promise<InventoryResult<InventoryMovement>> { const [materials, movements, purchases] = await Promise.all([this.store.listMaterials(), this.store.listInventoryMovements(), this.store.listSupplierPurchases()]); if (!materials.ok || !movements.ok || !purchases.ok) return storageFailure(); const repeated = movements.value.find((movement) => movement.operationKey === input.operationKey); if (repeated) return { ok: true, value: repeated, reused: true }; if (!materials.value.some((material) => material.id === input.materialId)) return { ok: false, code: "validation_error", message: "اختر مادة موجودة قبل استلام الشراء." }; const purchase = purchases.value.find((candidate) => candidate.id === input.purchaseId); if (!purchase) return { ok: false, code: "validation_error", message: "اختر شراء مواد موجودًا لاستلامه." }; const receivedValue = movements.value.filter((movement) => movement.type === "purchase_receipt" && movement.purchaseId === input.purchaseId).reduce((sum, movement) => sum + movement.valueDeltaMinor, 0); if (receivedValue + input.valueMinor > purchase.totalMinor) return { ok: false, code: "validation_error", message: "قيمة الاستلام تتجاوز إجمالي شراء المواد المرجعي." }; try { const movement = createInventoryMovement({ id: id("receipt"), materialId: input.materialId, type: "purchase_receipt", occurredOn: input.occurredOn, recordedAt: this.now(), quantityDeltaMilli: input.quantityMilli, valueDeltaMinor: input.valueMinor, note: input.note, operationKey: input.operationKey, purchaseId: input.purchaseId }); const saved = await this.store.commitInventory(null, [movement]); return saved.ok ? { ok: true, value: movement } : storageFailure(); } catch (error) { return { ok: false, code: "validation_error", message: error instanceof Error ? error.message : "بيانات استلام الشراء غير صالحة." }; } }
  async consume(input: ConsumeMaterialInput): Promise<InventoryResult<InventoryMovement>> { const [materials, movements, order] = await Promise.all([this.store.listMaterials(), this.store.listInventoryMovements(), this.store.getOrder(input.orderId)]); if (!materials.ok || !movements.ok || !order.ok) return storageFailure(); const repeated = movements.value.find((movement) => movement.operationKey === input.operationKey); if (repeated) return { ok: true, value: repeated, reused: true }; if (!materials.value.some((material) => material.id === input.materialId)) return { ok: false, code: "validation_error", message: "اختر مادة موجودة قبل تسجيل الاستهلاك." }; if (!order.value) return { ok: false, code: "validation_error", message: "اختر طلبًا محليًا موجودًا لاستهلاك المادة." }; try { const position = assertInventoryRemainsNonNegative(input.materialId, movements.value); const value = consumptionValueMinor(input.quantityMilli, position); const movement = createInventoryMovement({ id: id("consume"), materialId: input.materialId, type: "consumption", occurredOn: input.occurredOn, recordedAt: this.now(), quantityDeltaMilli: -input.quantityMilli, valueDeltaMinor: -value, note: input.note, operationKey: input.operationKey, orderId: input.orderId }); const saved = await this.store.commitInventory(null, [movement]); return saved.ok ? { ok: true, value: movement } : storageFailure(); } catch (error) { return { ok: false, code: "validation_error", message: error instanceof Error ? error.message : "بيانات استهلاك المادة غير صالحة." }; } }
  async waste(input: WasteMaterialInput): Promise<InventoryResult<InventoryMovement>> { return this.outbound({ ...input, type: "waste" }); }
  async adjust(input: AdjustMaterialInput): Promise<InventoryResult<InventoryMovement>> { const [materials, movements] = await Promise.all([this.store.listMaterials(), this.store.listInventoryMovements()]); if (!materials.ok || !movements.ok) return storageFailure(); const repeated = movements.value.find((movement) => movement.operationKey === input.operationKey); if (repeated) return { ok: true, value: repeated, reused: true }; if (!materials.value.some((material) => material.id === input.materialId)) return { ok: false, code: "validation_error", message: "اختر مادة موجودة قبل ضبطها." }; try { const position = assertInventoryRemainsNonNegative(input.materialId, movements.value); let value: number; if (input.quantityDeltaMilli > 0) { if (!Number.isInteger(input.valueMinorWhenIncrease) || input.valueMinorWhenIncrease === null || input.valueMinorWhenIncrease <= 0) throw new Error("ضبط الزيادة يحتاج قيمة موجبة معلنة."); value = input.valueMinorWhenIncrease; } else { value = -consumptionValueMinor(Math.abs(input.quantityDeltaMilli), position); } const movement = createInventoryMovement({ id: id("adjust-material"), materialId: input.materialId, type: "adjustment", occurredOn: input.occurredOn, recordedAt: this.now(), quantityDeltaMilli: input.quantityDeltaMilli, valueDeltaMinor: value, note: input.note, reason: input.reason, operationKey: input.operationKey }); assertInventoryRemainsNonNegative(input.materialId, [...movements.value, movement]); const saved = await this.store.commitInventory(null, [movement]); return saved.ok ? { ok: true, value: movement } : storageFailure(); } catch (error) { return { ok: false, code: "validation_error", message: error instanceof Error ? error.message : "بيانات ضبط المادة غير صالحة." }; } }
  async reverse(input: ReverseInventoryInput): Promise<InventoryResult<InventoryMovement>> { const movementsResult = await this.store.listInventoryMovements(); if (!movementsResult.ok) return storageFailure(); const movements = movementsResult.value; const repeated = movements.find((movement) => movement.operationKey === input.operationKey); if (repeated) return { ok: true, value: repeated, reused: true }; const target = movements.find((movement) => movement.id === input.movementId); if (!target) return { ok: false, code: "validation_error", message: "لم نجد حركة المادة التي تريد عكسها." }; if (target.type === "reversal" || movements.some((movement) => movement.reversesMovementId === target.id)) return { ok: false, code: "validation_error", message: "تم عكس هذه الحركة سابقًا ولا يمكن عكسها مرة ثانية." }; try { const reversal = createInventoryMovement({ id: id("reverse-material"), materialId: target.materialId, type: "reversal", occurredOn: input.occurredOn, recordedAt: this.now(), quantityDeltaMilli: -target.quantityDeltaMilli, valueDeltaMinor: -target.valueDeltaMinor, note: `عكس: ${target.note}`, reason: input.reason, operationKey: input.operationKey, reversesMovementId: target.id }); assertInventoryRemainsNonNegative(target.materialId, [...movements, reversal]); const saved = await this.store.commitInventory(null, [reversal]); return saved.ok ? { ok: true, value: reversal } : storageFailure(); } catch (error) { return { ok: false, code: "validation_error", message: error instanceof Error ? error.message : "بيانات عكس المادة غير صالحة." }; } }
  private async outbound(input: WasteMaterialInput & { type: "waste" }): Promise<InventoryResult<InventoryMovement>> { const [materials, movements] = await Promise.all([this.store.listMaterials(), this.store.listInventoryMovements()]); if (!materials.ok || !movements.ok) return storageFailure(); const repeated = movements.value.find((movement) => movement.operationKey === input.operationKey); if (repeated) return { ok: true, value: repeated, reused: true }; if (!materials.value.some((material) => material.id === input.materialId)) return { ok: false, code: "validation_error", message: "اختر مادة موجودة قبل تسجيل الهدر." }; try { const position = assertInventoryRemainsNonNegative(input.materialId, movements.value); const value = consumptionValueMinor(input.quantityMilli, position); const movement = createInventoryMovement({ id: id("waste"), materialId: input.materialId, type: input.type, occurredOn: input.occurredOn, recordedAt: this.now(), quantityDeltaMilli: -input.quantityMilli, valueDeltaMinor: -value, note: input.note, reason: input.reason, operationKey: input.operationKey }); const saved = await this.store.commitInventory(null, [movement]); return saved.ok ? { ok: true, value: movement } : storageFailure(); } catch (error) { return { ok: false, code: "validation_error", message: error instanceof Error ? error.message : "بيانات هدر المادة غير صالحة." }; } }
}
