import { describe, expect, it } from "vitest";
import { InventoryMaterialService } from "./inventoryMaterialService";
import { MemoryLocalStore } from "@/storage/local/MemoryLocalStore";
import { calculateCostSnapshot, createCraftOrder } from "@micro-domain/craft-order/index.js";
import { createSupplierPurchase } from "@micro-domain/supplier-purchase/index.js";

describe("InventoryMaterialService", () => {
  it("keeps purchase cash semantics separate while receiving, consuming, wasting, and reversing stock", async () => {
    const store = new MemoryLocalStore(); const service = new InventoryMaterialService(store, () => "2026-08-23T09:00:00.000Z"); const opened = await service.openMaterial({ name: "خشب", unit: "piece", openingQuantityMilli: 10000, openingValueMinor: 4000, occurredOn: "2026-08-01", note: "افتتاح", operationKey: "material-1" }); if (!opened.ok) throw new Error("material should open");
    const purchase = createSupplierPurchase({ id: "purchase-1", supplierName: "المورد", note: "ألواح", purchasedOn: "2026-08-02", dueOn: null, totalMinor: 3000, initialPaidMinor: 0, recordedAt: "2026-08-23T09:00:00.000Z", idempotencyKey: "purchase-1" }); await store.saveSupplierPurchase(purchase); await expect(service.receivePurchase({ materialId: opened.value.material.id, purchaseId: purchase.id, quantityMilli: 5000, valueMinor: 3000, occurredOn: "2026-08-02", note: "استلام ألواح", operationKey: "receipt-1" })).resolves.toMatchObject({ ok: true, value: { type: "purchase_receipt", valueDeltaMinor: 3000 } });
    const cost = calculateCostSnapshot("cost", { currency: "JOD", materialItems: [], time: { minutes: 60, hourlyRateMinor: 500, confidence: "known" }, packagingMinor: 0, deliveryMinor: 0, wasteMinor: 0, safetyBufferMinor: 0, quantity: 1, createdAt: "2026-08-23T09:00:00.000Z", freshnessDays: null }); const order = createCraftOrder({ id: "order-1", customerName: "سارة", itemName: "قطعة", specifications: "طلب اختبار", quantity: 1, agreedPriceMinor: 2000, costSnapshot: cost, createdAt: "2026-08-23T09:00:00.000Z" }); await store.saveOrder({ id: order.id, order, deliveryDate: "2026-08-30", agreementSource: null, createdAt: "2026-08-23T09:00:00.000Z", updatedAt: "2026-08-23T09:00:00.000Z" });
    await expect(service.consume({ materialId: opened.value.material.id, orderId: order.id, quantityMilli: 2000, occurredOn: "2026-08-23", note: "طلب سارة", operationKey: "consume-1" })).resolves.toMatchObject({ ok: true, value: { type: "consumption", quantityDeltaMilli: -2000, orderId: order.id } }); const waste = await service.waste({ materialId: opened.value.material.id, quantityMilli: 1000, occurredOn: "2026-08-23", note: "لوح تالف", reason: "كسر", operationKey: "waste-1" }); if (!waste.ok) throw new Error("waste should save"); await expect(service.reverse({ movementId: waste.value.id, occurredOn: "2026-08-23", reason: "سجل الهدر خاطئ", operationKey: "reverse-waste" })).resolves.toMatchObject({ ok: true, value: { type: "reversal", quantityDeltaMilli: 1000 } });
    const overview = await service.overview(); expect(overview).toMatchObject({ ok: true, value: { materials: [{ quantityMilli: 13000, valueMinor: 6067 }], truth: expect.stringContaining("ليست مصروفًا") } }); await expect(store.listSupplierPurchases()).resolves.toMatchObject({ ok: true, value: [{ id: purchase.id, paidMinor: 0, payableMinor: 3000 }] });
  });

  it("refuses an outbound movement greater than the quantity currently available", async () => { const service = new InventoryMaterialService(new MemoryLocalStore()); const opened = await service.openMaterial({ name: "خيط", unit: "meter", openingQuantityMilli: 1000, openingValueMinor: 500, occurredOn: "2026-08-01", note: "افتتاح", operationKey: "thread" }); if (!opened.ok) throw new Error("material should open"); await expect(service.waste({ materialId: opened.value.material.id, quantityMilli: 1001, occurredOn: "2026-08-23", note: "هدر", reason: "اختبار", operationKey: "too-much" })).resolves.toMatchObject({ ok: false, code: "validation_error" }); });
});
