/** Browser persistence adapter. React never imports this module and financial policy lives above it. */
import type { FinancialEvent } from "@micro-domain/financial-event/index.js";
import { localSchemaVersion, type ActivityProfile, type LocalPreferences, type LocalStoreSnapshot, type OrderDraft, type PrototypeLocalStore, type ScheduleEntry, type StorageFailure, type StorageResult, type StoredCraftOrder } from "./types";

const databaseName = "micro-prototype-local";
const profileStore = "activity-profile";
const preferencesStore = "local-preferences";
const draftStore = "order-drafts";
const orderStore = "craft-orders";
const scheduleStore = "schedule-entries";
const financialEventStore = "financial-events";

function failure(error: unknown): StorageFailure { return { ok: false, code: typeof indexedDB === "undefined" ? "storage_unavailable" : "storage_error", message: error instanceof Error ? error.message : "تعذر الوصول إلى التخزين المحلي." }; }
function openDatabase(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { if (typeof indexedDB === "undefined") { reject(new Error("التخزين المحلي غير مدعوم في هذا المتصفح.")); return; } const request = indexedDB.open(databaseName, localSchemaVersion); request.onerror = () => reject(request.error ?? new Error("تعذر فتح التخزين المحلي.")); request.onblocked = () => reject(new Error("التخزين المحلي مفتوح في نافذة أخرى.")); request.onupgradeneeded = event => { const database = request.result; if (!database.objectStoreNames.contains(profileStore)) database.createObjectStore(profileStore, { keyPath: "id" }); if (!database.objectStoreNames.contains(preferencesStore)) database.createObjectStore(preferencesStore, { keyPath: "id" }); if (!database.objectStoreNames.contains(draftStore)) { const drafts = database.createObjectStore(draftStore, { keyPath: "id" }); drafts.createIndex("updatedAt", "updatedAt"); } if (!database.objectStoreNames.contains(orderStore)) { const orders = database.createObjectStore(orderStore, { keyPath: "id" }); orders.createIndex("updatedAt", "updatedAt"); } if (!database.objectStoreNames.contains(scheduleStore)) { const schedules = database.createObjectStore(scheduleStore, { keyPath: "id" }); schedules.createIndex("scheduledFor", "scheduledFor"); schedules.createIndex("orderId", "orderId"); } if (!database.objectStoreNames.contains(financialEventStore)) { const events = database.createObjectStore(financialEventStore, { keyPath: "id" }); events.createIndex("recordedAt", "recordedAt"); events.createIndex("occurredOn", "occurredOn"); } if (event.oldVersion < 4) { const drafts = request.transaction?.objectStore(draftStore); if (!drafts) return; const cursor = drafts.openCursor(); cursor.onsuccess = () => { const current = cursor.result; if (!current) return; const legacy = current.value as Partial<OrderDraft>; current.update({ ...legacy, costSnapshots: Array.isArray(legacy.costSnapshots) ? legacy.costSnapshots : [], activeCostSnapshotId: legacy.activeCostSnapshotId ?? null, linkedOrderId: legacy.linkedOrderId ?? null }); current.continue(); }; } }; request.onsuccess = () => resolve(request.result); }); }
async function readOne<T>(storeName: string, key: string): Promise<StorageResult<T | null>> { try { const database = await openDatabase(); return await new Promise(resolve => { const transaction = database.transaction(storeName, "readonly"); const request = transaction.objectStore(storeName).get(key); request.onerror = () => resolve(failure(request.error)); request.onsuccess = () => resolve({ ok: true, value: (request.result as T | undefined) ?? null }); transaction.oncomplete = () => database.close(); }); } catch (error) { return failure(error); } }
async function writeOne<T>(storeName: string, value: T): Promise<StorageResult<T>> { try { const database = await openDatabase(); return await new Promise(resolve => { const transaction = database.transaction(storeName, "readwrite"); const request = transaction.objectStore(storeName).put(value); request.onerror = () => resolve(failure(request.error)); transaction.onabort = () => resolve(failure(transaction.error)); transaction.oncomplete = () => { database.close(); resolve({ ok: true, value }); }; }); } catch (error) { return failure(error); } }
async function listAll<T>(storeName: string, sort: (left: T, right: T) => number): Promise<StorageResult<readonly T[]>> { try { const database = await openDatabase(); return await new Promise(resolve => { const transaction = database.transaction(storeName, "readonly"); const request = transaction.objectStore(storeName).getAll(); request.onerror = () => resolve(failure(request.error)); request.onsuccess = () => resolve({ ok: true, value: (request.result as T[]).sort(sort) }); transaction.oncomplete = () => database.close(); }); } catch (error) { return failure(error); } }

export class IndexedDbLocalStore implements PrototypeLocalStore {
  getProfile() { return readOne<ActivityProfile>(profileStore, "local-profile"); }
  saveProfile(profile: ActivityProfile) { return writeOne(profileStore, profile); }
  getPreferences() { return readOne<LocalPreferences>(preferencesStore, "local-preferences"); }
  savePreferences(preferences: LocalPreferences) { return writeOne(preferencesStore, preferences); }
  listDrafts() { return listAll<OrderDraft>(draftStore, (a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
  getDraft(id: string) { return readOne<OrderDraft>(draftStore, id); }
  saveDraft(draft: OrderDraft) { return writeOne(draftStore, draft); }
  listOrders() { return listAll<StoredCraftOrder>(orderStore, (a, b) => b.updatedAt.localeCompare(a.updatedAt)); }
  getOrder(id: string) { return readOne<StoredCraftOrder>(orderStore, id); }
  saveOrder(order: StoredCraftOrder) { return writeOne(orderStore, order); }
  listSchedules() { return listAll<ScheduleEntry>(scheduleStore, (a, b) => a.scheduledFor.localeCompare(b.scheduledFor) || b.updatedAt.localeCompare(a.updatedAt)); }
  getSchedule(id: string) { return readOne<ScheduleEntry>(scheduleStore, id); }
  saveSchedule(schedule: ScheduleEntry) { return writeOne(scheduleStore, schedule); }
  listFinancialEvents() { return listAll<FinancialEvent>(financialEventStore, (a, b) => b.recordedAt.localeCompare(a.recordedAt)); }
  getFinancialEvent(id: string) { return readOne<FinancialEvent>(financialEventStore, id); }
  saveFinancialEvent(event: FinancialEvent) { return writeOne(financialEventStore, event); }
  async commitOrderFromDraft(order: StoredCraftOrder, draft: OrderDraft, schedule?: ScheduleEntry): Promise<StorageResult<{ order: StoredCraftOrder; draft: OrderDraft; schedule: ScheduleEntry | null }>> { try { const database = await openDatabase(); return await new Promise(resolve => { const stores = schedule ? [orderStore, draftStore, scheduleStore] : [orderStore, draftStore]; const transaction = database.transaction(stores, "readwrite"); transaction.objectStore(orderStore).put(order); transaction.objectStore(draftStore).put(draft); if (schedule) transaction.objectStore(scheduleStore).put(schedule); transaction.onabort = () => resolve(failure(transaction.error)); transaction.onerror = () => resolve(failure(transaction.error)); transaction.oncomplete = () => { database.close(); resolve({ ok: true, value: { order, draft, schedule: schedule ?? null } }); }; }); } catch (error) { return failure(error); } }
  async readSnapshot(): Promise<StorageResult<LocalStoreSnapshot>> { try { const database = await openDatabase(); return await new Promise(resolve => { const transaction = database.transaction([profileStore, preferencesStore, draftStore, orderStore, scheduleStore, financialEventStore], "readonly"); const profile = transaction.objectStore(profileStore).get("local-profile"); const preferences = transaction.objectStore(preferencesStore).get("local-preferences"); const drafts = transaction.objectStore(draftStore).getAll(); const orders = transaction.objectStore(orderStore).getAll(); const schedules = transaction.objectStore(scheduleStore).getAll(); const financialEvents = transaction.objectStore(financialEventStore).getAll(); transaction.onerror = () => resolve(failure(transaction.error)); transaction.onabort = () => resolve(failure(transaction.error)); transaction.oncomplete = () => { database.close(); resolve({ ok: true, value: { profile: (profile.result as ActivityProfile | undefined) ?? null, preferences: (preferences.result as LocalPreferences | undefined) ?? null, drafts: drafts.result as OrderDraft[], orders: orders.result as StoredCraftOrder[], schedules: schedules.result as ScheduleEntry[], financialEvents: financialEvents.result as FinancialEvent[] } }); }; }); } catch (error) { return failure(error); } }
  async replaceSnapshot(snapshot: LocalStoreSnapshot): Promise<StorageResult<LocalStoreSnapshot>> { try { const database = await openDatabase(); const normalized: LocalStoreSnapshot = { ...snapshot, schedules: snapshot.schedules ?? [], financialEvents: snapshot.financialEvents ?? [] }; return await new Promise(resolve => { const transaction = database.transaction([profileStore, preferencesStore, draftStore, orderStore, scheduleStore, financialEventStore], "readwrite"); const profiles = transaction.objectStore(profileStore); const preferences = transaction.objectStore(preferencesStore); const drafts = transaction.objectStore(draftStore); const orders = transaction.objectStore(orderStore); const schedules = transaction.objectStore(scheduleStore); const financialEvents = transaction.objectStore(financialEventStore); profiles.clear(); preferences.clear(); drafts.clear(); orders.clear(); schedules.clear(); financialEvents.clear(); if (normalized.profile) profiles.put(normalized.profile); if (normalized.preferences) preferences.put(normalized.preferences); normalized.drafts.forEach(draft => drafts.put(draft)); normalized.orders.forEach(order => orders.put(order)); normalized.schedules.forEach(schedule => schedules.put(schedule)); normalized.financialEvents.forEach(event => financialEvents.put(event)); transaction.onerror = () => resolve(failure(transaction.error)); transaction.onabort = () => resolve(failure(transaction.error)); transaction.oncomplete = () => { database.close(); resolve({ ok: true, value: normalized }); }; }); } catch (error) { return failure(error); } }
}
