/** Slice 3 agreement: converts a saved local draft into one CraftOrder with an explicit date and optional collected deposit. */
import { ArrowRight, CircleAlert, Save } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation, useParams } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import type { OrderDraft } from "@/storage/local/types";

const money = new Intl.NumberFormat("ar-JO", { style: "currency", currency: "JOD", minimumFractionDigits: 2 });
const minor = (value: string) => Math.round((Number(value) || 0) * 100);
const major = (value: number) => (value / 100).toFixed(2);

export default function AgreementEditor() {
  const params = useParams<{ id: string }>(); const [, navigate] = useLocation(); const { drafts, costs, agreements, dataVersion, notifyDataChanged } = usePrototypeServices();
  const [draft, setDraft] = useState<OrderDraft | null>(null); const [price, setPrice] = useState(""); const [deliveryDate, setDeliveryDate] = useState(""); const [deposit, setDeposit] = useState("0.00"); const [source, setSource] = useState("conversation"); const [acknowledgesBelowFloor, setAcknowledgesBelowFloor] = useState(false); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [message, setMessage] = useState<string | null>(null); const [isSaving, setIsSaving] = useState(false);
  useEffect(() => { let active = true; drafts.get(params.id).then(result => { if (!active) return; if (!result.ok || !result.value) { setState("error"); return; } const loaded = result.value; if (loaded.linkedOrderId) { navigate(`/orders/${loaded.linkedOrderId}`); return; } setDraft(loaded); const snapshot = loaded.costSnapshots.find(item => item.id === loaded.activeCostSnapshotId); const preview = snapshot ? costs.previewStored(snapshot) : null; if (preview?.ok) setPrice(major(preview.snapshot.priceFloorMinor * loaded.quantity)); setState("ready"); }); return () => { active = false; }; }, [costs, dataVersion, drafts, navigate, params.id]);
  const snapshot = draft?.costSnapshots.find(item => item.id === draft.activeCostSnapshotId) ?? null; const preview = useMemo(() => snapshot ? costs.previewStored(snapshot) : null, [costs, snapshot]); const floor = preview?.ok ? preview.snapshot.priceFloorMinor * (draft?.quantity ?? 1) : null; const isBelowFloor = floor !== null && minor(price) < floor;
  if (state === "loading") return <div className="micro-route-loading" role="status">جارٍ فتح الاتفاق…</div>;
  if (state === "error" || !draft || !preview?.ok) return <section className="micro-page micro-not-found"><h1>التكلفة المطلوبة غير متاحة</h1><p>احفظ Snapshot تكلفة صالحًا قبل تثبيت الاتفاق.</p><button className="micro-button micro-button-primary" type="button" onClick={() => navigate(`/orders/draft/${params.id}/cost`)}>فتح التكلفة</button></section>;
  async function submit() { if (!draft) return; setMessage(null); if (isBelowFloor && !acknowledgesBelowFloor) { setMessage("أكد أنك راجعت السعر الأقل من سعر الحماية قبل تثبيت الاتفاق."); return; } setIsSaving(true); const result = await agreements.createFromDraft(draft, { agreedPriceMinor: minor(price), deliveryDate, depositMinor: minor(deposit), agreementSource: source }); setIsSaving(false); if (!result.ok) { setMessage(result.message); return; } notifyDataChanged(); navigate(`/orders/${result.stored.id}`); }
  return <section className="micro-page micro-agreement-page"><button className="micro-back-button" type="button" onClick={() => navigate(`/orders/draft/${draft.id}/cost`)}><ArrowRight aria-hidden="true" /> العودة للتكلفة</button><div className="micro-page-heading"><span className="micro-overline">اتفاق محلي</span><h1>ثبّت ما اتفقت عليه</h1><p>السعر والموعد والعربون تصبح أحداثًا مرتبطة بهذا الطلب فقط.</p></div><section className="micro-cost-result" data-knowledge={preview.snapshot.knowledgeState}><span>سعر الحماية لهذه الكمية</span><strong>{money.format((floor ?? 0) / 100)}</strong><small>{preview.snapshot.knowledgeState === "known" ? "تكلفة معروفة من البيانات المدخلة." : "درجة معرفة التكلفة ليست نهائية؛ راجع الافتراضات قبل تثبيت السعر."}</small></section><section className="micro-form-card"><label className="micro-field"><span>السعر المتفق عليه (د.أ)</span><input type="number" min="0.01" step="0.01" inputMode="decimal" value={price} onChange={event => setPrice(event.target.value)} /></label>{isBelowFloor ? <label className="micro-confirm-warning"><input type="checkbox" checked={acknowledgesBelowFloor} onChange={event => setAcknowledgesBelowFloor(event.target.checked)} /><span><b>السعر أقل من سعر الحماية.</b> راجعت السبب وأريد تسجيل الاتفاق كما هو.</span></label> : null}<label className="micro-field"><span>موعد التسليم</span><input type="date" value={deliveryDate} onChange={event => setDeliveryDate(event.target.value)} /></label><label className="micro-field"><span>العربون المحصل الآن (د.أ) <small>اختياري</small></span><input type="number" min="0" step="0.01" inputMode="decimal" value={deposit} onChange={event => setDeposit(event.target.value)} /></label><p className="micro-deposit-truth"><CircleAlert aria-hidden="true" /> العربون كاش محصل مرتبط بالطلب، وليس ربحًا نهائيًا أو تسليمًا تلقائيًا.</p><label className="micro-field"><span>كيف تم الاتفاق؟</span><select value={source} onChange={event => setSource(event.target.value)}><option value="conversation">محادثة</option><option value="call">مكالمة</option><option value="in_person">لقاء مباشر</option><option value="other">أخرى</option></select></label>{message ? <p className="micro-field-error" role="alert">{message}</p> : null}<button className="micro-button micro-button-primary micro-save-cost" type="button" disabled={isSaving || minor(price) <= 0 || !deliveryDate} onClick={submit}><Save aria-hidden="true" />{isSaving ? "جارٍ تثبيت الاتفاق…" : "تثبيت الاتفاق"}</button></section></section>;
}
