/** Style: Micro «مسار القرار» — introduce one declared cash location without confusing it with sales or capital. */
/* مبدأ Micro: يظل رصيد البداية أثرًا محليًا واضحًا، ويعرض تاريخه دون تغيير معناه المالي. */
import { ArrowRight, Save, WalletCards } from "lucide-react";
import { useRef, useState } from "react";
import { useLocation } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import { EnglishNumberInput } from "@/components/forms/EnglishNumberInput";
import { LocalDateField } from "@/components/forms/LocalDateField";
import type { CashWalletKind } from "@micro-domain/cash-continuity/index.js";
import { localDateInAmman } from "@/presentation/formatters";
export default function CashWalletEditor() { const [, navigate] = useLocation(); const { cashContinuity, notifyDataChanged } = usePrototypeServices(); const [name, setName] = useState(""); const [kind, setKind] = useState<CashWalletKind>("cash_drawer"); const [openingMinor, setOpeningMinor] = useState(0); const [validAmount, setValidAmount] = useState(true); const [date, setDate] = useState(() => localDateInAmman()); const [note, setNote] = useState("رصيد بداية معلن"); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false); const operationKey = useRef(`cash-wallet-ui-${globalThis.crypto?.randomUUID?.() ?? Date.now()}`);
  async function save() { if (!name.trim() || !note.trim() || !validAmount || openingMinor < 0) { setMessage("أدخل اسم المحفظة ورصيد بداية صالحًا بالأرقام 0–9."); return; } setSaving(true); const result = await cashContinuity.openWallet({ name, kind, openingMinor, occurredOn: date, note, operationKey: operationKey.current }); setSaving(false); if (!result.ok) { setMessage(result.message); return; } notifyDataChanged(); navigate("/cash"); }
  return <section className="micro-page micro-finance-page"><button className="micro-back-button" type="button" onClick={() => navigate("/cash")}><ArrowRight aria-hidden="true" /> محافظ الكاش</button><div className="micro-page-heading"><span className="micro-overline">بداية معلنة</span><h1>أين يوجد الكاش الآن؟</h1><p>أضف المكان والمبلغ كما تعرفهما في يوم البدء. لا يعالج هذا ربحًا أو مبيعات سابقة.</p></div><section className="micro-decision-card"><WalletCards aria-hidden="true" /><div><span>حد الحقيقة</span><strong>رصيد البداية ليس مال مالك ولا دخلًا.</strong><p>إنه نقطة واضحة لتبدأ منها مراجعة كاش مشروعك على هذا الجهاز.</p></div></section><section className="micro-form-card"><label className="micro-field"><span>اسم المحفظة</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder="مثال: درج الورشة" /></label><label className="micro-field"><span>نوع المكان</span><select value={kind} onChange={(event) => setKind(event.target.value as CashWalletKind)}><option value="cash_drawer">درج كاش</option><option value="bank_account">حساب بنكي</option><option value="digital_wallet">محفظة رقمية</option><option value="other">مكان آخر</option></select></label><label className="micro-field"><span>رصيد البداية بالدينار الأردني</span><EnglishNumberInput value={openingMinor} kind="money" onNumericChange={setOpeningMinor} onTextValidityChange={setValidAmount} aria-label="رصيد البداية" /><small>يمكن أن يكون صفرًا إذا أردت تعريف المكان الآن فقط.</small></label><LocalDateField label="تاريخ البداية" value={date} onChange={(event) => setDate(event.target.value)} /><label className="micro-field"><span>بيان مختصر</span><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="مثال: عدّ الدرج في بداية استخدام Micro" /></label>{message ? <p className="micro-field-error" role="status">{message}</p> : null}<button className="micro-button micro-button-primary micro-save-cost" type="button" disabled={saving} onClick={save}><Save aria-hidden="true" />{saving ? "جارٍ الحفظ…" : "حفظ محفظة ورصيد البداية"}</button></section></section>; }
