/** Style: Micro «مسار القرار» — a transfer has two visible sides and never changes total cash. */
import { ArrowRight, ArrowRightLeft, Save } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useLocation } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import { EnglishNumberInput } from "@/components/forms/EnglishNumberInput";
import type { CashWalletBalance } from "@/application/cash/cashContinuityService";
import { MoneyValue } from "@/components/presentation/DisplayValue";
import { localDateInAmman } from "@/presentation/formatters";
export default function CashTransferEditor() { const [, navigate] = useLocation(); const { cashContinuity, notifyDataChanged } = usePrototypeServices(); const [wallets, setWallets] = useState<readonly CashWalletBalance[]>([]); const [fromWalletId, setFromWalletId] = useState(""); const [toWalletId, setToWalletId] = useState(""); const [amountMinor, setAmountMinor] = useState(0); const [validAmount, setValidAmount] = useState(true); const [date, setDate] = useState(() => localDateInAmman()); const [note, setNote] = useState(""); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false); const operationKey = useRef(`cash-transfer-ui-${globalThis.crypto?.randomUUID?.() ?? Date.now()}`);
  useEffect(() => { cashContinuity.overview().then((result) => { if (!result.ok) { setMessage(result.message); return; } setWallets(result.value.wallets); setFromWalletId(result.value.wallets[0]?.id ?? ""); setToWalletId(result.value.wallets[1]?.id ?? ""); }); }, [cashContinuity]);
  async function save() { if (!validAmount || amountMinor <= 0 || !note.trim()) { setMessage("أدخل مبلغ التحويل وبيانًا قصيرًا بالأرقام الإنجليزية."); return; } setSaving(true); const result = await cashContinuity.transfer({ fromWalletId, toWalletId, amountMinor, occurredOn: date, note, operationKey: operationKey.current }); setSaving(false); if (!result.ok) { setMessage(result.message); return; } notifyDataChanged(); navigate("/cash"); }
  if (wallets.length < 2) return <section className="micro-page micro-not-found"><h1>تحتاج محافظتين للتحويل</h1><p>أضف مكان كاش آخر أولًا؛ التحويل لا ينشئ كاشًا جديدًا.</p><button className="micro-button micro-button-primary" type="button" onClick={() => navigate("/cash/wallet/new")}>أضف محفظة</button></section>;
  return <section className="micro-page micro-finance-page"><button className="micro-back-button" type="button" onClick={() => navigate("/cash")}><ArrowRight aria-hidden="true" /> محافظ الكاش</button><div className="micro-page-heading"><span className="micro-overline">حركة داخلية</span><h1>حوّل كاشًا بين محافظك</h1><p>ينقص مصدر التحويل ويزيد وجهته بالمبلغ نفسه. لا يغير الكاش الكلي أو الربح أو المصروف.</p></div><section className="micro-decision-card"><ArrowRightLeft aria-hidden="true" /><div><span>حد الحقيقة</span><strong>التحويل ليس دخلاً ولا مصروفًا.</strong><p>سيظهر طرفا الحركة معًا في السجل حتى يمكن عكسهما بأمان.</p></div></section><section className="micro-form-card"><label className="micro-field"><span>من محفظة</span><select value={fromWalletId} onChange={(event) => setFromWalletId(event.target.value)}>{wallets.map((wallet) => <option key={wallet.id} value={wallet.id}>{wallet.name} · <MoneyValue minor={wallet.balanceMinor} className="micro-inline-number" /></option>)}</select></label><label className="micro-field"><span>إلى محفظة</span><select value={toWalletId} onChange={(event) => setToWalletId(event.target.value)}>{wallets.map((wallet) => <option key={wallet.id} value={wallet.id}>{wallet.name} · <MoneyValue minor={wallet.balanceMinor} className="micro-inline-number" /></option>)}</select></label><label className="micro-field"><span>مبلغ التحويل (د.أ)</span><EnglishNumberInput value={amountMinor} kind="money" onNumericChange={setAmountMinor} onTextValidityChange={setValidAmount} aria-label="مبلغ التحويل" /></label><label className="micro-field"><span>تاريخ التحويل</span><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="micro-field"><span>ما الذي حدث؟</span><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="مثال: أودعت كاش الدرج في الحساب البنكي" /></label>{message ? <p className="micro-field-error" role="status">{message}</p> : null}<button className="micro-button micro-button-primary micro-save-cost" type="button" disabled={saving} onClick={save}><Save aria-hidden="true" />{saving ? "جارٍ الحفظ…" : "حفظ التحويل"}</button></section></section>; }
