/** Style: Micro «مسار القرار» — phone-first RTL, evidence-led financial reading; G5 keeps figures derived and explicitly bounded. */
import { ArrowLeft, CircleDollarSign, HandCoins, Landmark, ReceiptText, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import type { FinancialInsights, ProjectFinancialPosition, RecordedPeriodResult } from "@/application/finance/projectFinancialService";
import type { FinancialEvent, FinancialEventType } from "@micro-domain/financial-event/index.js";

type FinanceState = { phase: "loading" } | { phase: "error" } | { phase: "ready"; position: ProjectFinancialPosition; events: readonly FinancialEvent[]; period: RecordedPeriodResult; insights: FinancialInsights };
const money = new Intl.NumberFormat("en-JO", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const eventLabel: Record<FinancialEventType, string> = { owner_investment_cash: "استثمار المالك", owner_withdrawal_cash: "سحب شخصي", operating_expense_cash: "مصروف مدفوع", operating_expense_payable: "مصروف مستحق", payable_settlement_cash: "تسديد التزام" };
const expenseContextLabel = (event: FinancialEvent) => { if (event.operatingExpenseDeltaMinor <= 0) return null; if (!event.expenseContext) return "مصروف قديم غير مصنف"; const relationship = event.expenseContext.relationship === "shared" ? "حصة مشروع مشتركة" : "للمشروع"; const knowledge = event.expenseContext.knowledge === "known" ? "معروف" : event.expenseContext.knowledge === "estimated" ? "تقديري" : "يحتاج مراجعة"; return `${relationship} · ${knowledge}`; };
const currentMonth = () => { const parts = new Intl.DateTimeFormat("en", { timeZone: "Asia/Amman", year: "numeric", month: "2-digit" }).formatToParts(new Date()); const value = (type: string) => parts.find((part) => part.type === type)?.value; return `${value("year")}-${value("month")}`; };
function monthBounds(month: string) { const [year, numericMonth] = month.split("-").map(Number); const lastDay = new Date(Date.UTC(year!, numericMonth!, 0)).getUTCDate(); return { from: `${month}-01`, to: `${month}-${String(lastDay).padStart(2, "0")}` }; }
const formatted = (minor: number) => `${money.format(minor / 100)} د.أ`;

export default function Finance() {
  const [, navigate] = useLocation(); const { projectFinance, dataVersion } = usePrototypeServices(); const [month, setMonth] = useState(currentMonth); const [state, setState] = useState<FinanceState>({ phase: "loading" });
  useEffect(() => { let active = true; const bounds = monthBounds(month); Promise.all([projectFinance.readPosition(), projectFinance.listEvents(), projectFinance.readRecordedPeriodResult(bounds.from, bounds.to), projectFinance.readFinancialInsights(bounds.from, bounds.to)]).then(([position, events, result, insights]) => { if (!active) return; if (!position.ok || !events.ok || !result.ok || !insights.ok) { setState({ phase: "error" }); return; } setState({ phase: "ready", position: position.value, events: events.value, period: result.value, insights: insights.value }); }); return () => { active = false; }; }, [dataVersion, month, projectFinance]);
  if (state.phase === "loading") return <div className="micro-route-loading" role="status">جارٍ قراءة الوضع المالي المحلي…</div>;
  if (state.phase === "error") return <section className="micro-page micro-not-found"><h1>تعذر قراءة الوضع المالي</h1><p>لم يتم تغيير بياناتك. أعد فتح التطبيق للمحاولة.</p><button className="micro-button micro-button-primary" type="button" onClick={() => navigate("/")}>مشروعي الآن</button></section>;
  const { position, period, insights } = state;
  return <section className="micro-page micro-finance-page">
    <button className="micro-back-button" type="button" onClick={() => navigate("/")}><ArrowLeft aria-hidden="true" /> مشروعي الآن</button>
    <div className="micro-page-heading"><span className="micro-overline">الصورة العامة</span><h1>وضعي المالي الآن</h1><p>ليست هذه قيمة المشروع أو صافي ربحه؛ إنها صورة من الأحداث المحلية التي سجلتها حتى الآن.</p></div>
    <section className="micro-finance-position" aria-label="الوضع المالي المسجل"><PositionCard label="الكاش المسجل" value={position.recordedCashMinor} helper="محافظ معلنة + كاش غير موزع" icon={WalletCards} /><PositionCard label="لي عند العملاء" value={position.customerReceivablesMinor} helper="دين مسجل بعد التسليم" icon={HandCoins} /><PositionCard label="عليّ للموردين" value={position.supplierPayablesMinor} helper="مصروفات أو مشتريات مستحقة" icon={Landmark} /><PositionCard label="مال المالك المسجل" value={position.ownerCapitalRecordedMinor} helper="استثمار ناقص سحب شخصي" icon={CircleDollarSign} /></section>
    <section className="micro-finance-truth"><ReceiptText aria-hidden="true" /><div><h2>ما نعرفه الآن</h2><p>{position.truth}</p><p>كاش المحافظ المعلن: <span className="micro-number">{money.format(position.walletCashMinor / 100)}</span> د.أ · الكاش غير الموزع: <span className="micro-number">{money.format(position.unallocatedCashMinor / 100)}</span> د.أ · محافظ مسجلة: {position.cashWalletCount}</p><p>المصاريف التشغيلية المسجلة: <span className="micro-number">{money.format(position.operatingExpensesRecordedMinor / 100)}</span> د.أ · شراء مواد مسجل: {position.supplierPurchaseCount} · الأحداث العامة: {position.projectEventCount}</p></div></section>
    <section className="micro-period-result" data-status={period.status}><div className="micro-period-heading"><div><span className="micro-overline">النتيجة المسجلة</span><h2>نتيجة الفترة</h2></div><label><span>الشهر</span><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} aria-label="شهر نتيجة الفترة" /></label></div><p className="micro-period-result-value"><span>الإيراد − التكلفة − المصروفات المسجلة</span><strong className="micro-number" data-negative={period.resultMinor < 0}>{formatted(period.resultMinor)}</strong></p><dl><div><dt>إيراد طلبات نهائية</dt><dd className="micro-number">{money.format(period.recognizedRevenueMinor / 100)}</dd></div><div><dt>تكلفة مباشرة معترف بها</dt><dd className="micro-number">{money.format(period.recognizedDirectCostMinor / 100)}</dd></div><div><dt>مصروفات عامة مسجلة</dt><dd className="micro-number">{money.format(period.recordedOperatingExpenseMinor / 100)}</dd></div><div><dt>طلبات داخلة / مستبعدة</dt><dd className="micro-number">{period.finalOrderCount} / {period.excludedOrderCount}</dd></div></dl>{period.expenseNeedsReviewCount > 0 ? <p className="micro-period-review-note">{period.expenseNeedsReviewCount} مصروف مسجل يحتاج تصنيفًا أو مراجعة قبل الاعتماد على نتيجة أدق.</p> : null}<p className="micro-period-truth">{period.truth}</p></section>
    <FinancialInsightsPanel insights={insights} />
    <section className="micro-finance-actions" aria-label="تسجيل حدث مالي"><button className="micro-button micro-button-primary" type="button" onClick={() => navigate("/cash")}>محافظ الكاش والافتتاح</button><button className="micro-button micro-button-secondary" type="button" onClick={() => navigate("/suppliers")}>مشتريات المواد والموردون</button><button className="micro-button micro-button-secondary" type="button" onClick={() => navigate("/inventory")}>المواد والمخزون</button><button className="micro-button micro-button-secondary" type="button" onClick={() => navigate("/finance/new/operating_expense_cash")}>سجل مصروفًا مدفوعًا</button><button className="micro-button micro-button-secondary" type="button" onClick={() => navigate("/finance/new/operating_expense_payable")}>سجل التزامًا لمورد</button><button className="micro-button micro-button-secondary" type="button" onClick={() => navigate("/finance/new/owner_investment_cash")}>سجل استثمارًا</button><button className="micro-button micro-button-secondary" type="button" onClick={() => navigate("/finance/new/owner_withdrawal_cash")}>سجل سحبًا شخصيًا</button>{position.supplierPayablesMinor > 0 ? <button className="micro-button micro-button-secondary" type="button" onClick={() => navigate("/finance/new/payable_settlement_cash")}>سدد التزام مصروف</button> : null}</section>
    <section className="micro-finance-event-list"><div className="micro-finance-event-heading"><span className="micro-overline">السجل المحلي</span><h2>أحدث الأحداث العامة</h2></div>{state.events.length > 0 ? state.events.slice(0, 6).map((event) => <article key={event.id}><div><strong>{eventLabel[event.type]}</strong><small>{event.occurredOn} · {event.note}{expenseContextLabel(event) ? ` · ${expenseContextLabel(event)}` : ""}</small></div><b className="micro-number" data-negative={event.cashDeltaMinor < 0 || event.payableDeltaMinor > 0}>{event.amountMinor > 0 ? formatted(event.amountMinor) : "0.00 د.أ"}</b></article>) : <p>لم تسجل حدثًا عامًا بعد. سجّل واقعًا تعرفه، لا تقديرًا لا تثق به.</p>}</section>
  </section>;
}

function FinancialInsightsPanel({ insights }: { insights: FinancialInsights }) {
  const topWork = insights.workNames[0]; const coverageReady = insights.coverage.status === "recorded_only";
  return <section className="micro-section" aria-label="قراءة الفترة"><div className="micro-section-heading"><div><span className="micro-overline">قراءة الفترة</span><h2>الهامش والتغطية والسيولة</h2></div></div><article className="micro-info-card" data-tone={insights.period.status === "incomplete" ? "warning" : undefined}><div className="micro-card-copy"><span className="micro-card-eyebrow">حسب اسم العمل المسجل</span>{topWork ? <><h2>{topWork.itemName}</h2><p>هامش مباشر مسجل من {topWork.finalOrderCount} طلبات نهائية، لا يشمل تحميل المصروف العام أو حركة المخزون الفعلية.</p></> : <><h2>لا توجد أسماء عمل نهائية بعد</h2><p>يظهر هذا السطح عند تسليم طلب بنتيجة نهائية ضمن الشهر المختار.</p></>}</div>{topWork ? <div className="micro-record-summary"><div><span>الهامش المباشر</span><strong className="micro-number" data-negative={topWork.directMarginMinor < 0}>{formatted(topWork.directMarginMinor)}</strong></div><div><span>الكمية المسلّمة</span><strong className="micro-number">{topWork.deliveredQuantity}</strong></div></div> : null}<p>تركيب Snapshot المسجل: مواد {formatted(insights.costComposition.materialMinor)} · وقت {formatted(insights.costComposition.timeMinor)} · توصيل {formatted(insights.costComposition.deliveryMinor)}.</p></article><article className="micro-decision-panel" data-tone={coverageReady ? "accent" : "warning"}><div><span className="micro-decision-label">مؤشر تغطية الفترة</span><strong>{coverageReady ? `${insights.coverage.breakEvenUnits} وحدات من مزيج الفترة` : "لا يمكن إعطاء رقم تغطية الآن"}</strong><p>{coverageReady ? insights.coverage.truth : insights.coverage.reasons[0] ?? insights.coverage.truth}</p></div><p className="micro-decision-next">الفعل التالي: {coverageReady ? "راجع السعر والتكلفة عند تغير المزيج؛ الرقم ليس توقع مبيعات." : "أكمل درجة المعرفة أو تصنيف سلوك المصروف قبل الاعتماد على رقم."}</p></article><article className="micro-info-card"><div className="micro-card-copy"><span className="micro-card-eyebrow">السيولة المسجلة</span><h2>{insights.liquidity.status === "incomplete" ? "الكاش لا يساوي السيولة القادمة" : "التزامات مسجلة بلا ذمم حالية"}</h2><p>{insights.liquidity.truth}</p></div><div className="micro-record-summary"><div><span>تغطية الكاش بعد ما عليّ</span><strong className="micro-number" data-negative={insights.liquidity.cashCoverageAfterLiabilitiesMinor < 0}>{formatted(insights.liquidity.cashCoverageAfterLiabilitiesMinor)}</strong></div><div><span>ذمم العملاء منفصلة</span><strong className="micro-number">{formatted(insights.liquidity.customerReceivablesMinor)}</strong></div></div></article><p className="micro-cost-disclaimer">{insights.truth}</p></section>;
}

function PositionCard({ label, value, helper, icon: Icon }: { label: string; value: number; helper: string; icon: typeof WalletCards }) { return <article className="micro-finance-position-card"><Icon aria-hidden="true" /><span>{label}</span><strong className="micro-number" data-negative={value < 0}>{money.format(value / 100)}</strong><small>{helper}</small></article>; }
