/** Style: Micro «مسار القرار» — phone-first RTL surface, one honest action and financial labels with explicit scope. */
import { ArrowLeft, ClipboardPenLine } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import type { DailyFollowUp } from "@/application/follow-up/dailyFollowUpService";
import type { LocalFinancialPulse } from "@/application/financial-pulse/financialPulseService";
import type { ActivityProfile } from "@/storage/local/types";

type HomeState = { phase: "loading" } | { phase: "error" } | { phase: "ready"; profile: ActivityProfile; followUp: DailyFollowUp; pulse: LocalFinancialPulse };
const amount = new Intl.NumberFormat("en-JO", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const count = new Intl.NumberFormat("en-US", { useGrouping: false });

export default function Home() {
  const [, navigate] = useLocation(); const { profiles, financialPulse, dailyFollowUp, dataVersion } = usePrototypeServices(); const [state, setState] = useState<HomeState>({ phase: "loading" });
  useEffect(() => { let active = true; Promise.all([profiles.load(), financialPulse.read(), dailyFollowUp.read()]).then(([profile, pulseResult, followUpResult]) => { if (!active) return; if (!profile.ok || !pulseResult.ok || !followUpResult.ok || !profile.value) { setState({ phase: "error" }); return; } setState({ phase: "ready", profile: profile.value, followUp: followUpResult.followUp, pulse: pulseResult.pulse }); }); return () => { active = false; }; }, [dataVersion, dailyFollowUp, financialPulse, profiles]);
  if (state.phase === "loading") return <div className="micro-route-loading" role="status">جارٍ قراءة سجلات المشروع…</div>;
  if (state.phase === "error") return <section className="micro-page micro-not-found"><h1>تعذر تحميل سجلات المشروع</h1><p>لم يتم تغيير بياناتك. أعد فتح التطبيق للمحاولة.</p></section>;
  const priorityTone = state.followUp.kind === "recorded_debt" ? "warning" : "accent";
  return <section className="micro-page"><div className="micro-page-heading micro-home-heading"><span className="micro-overline">مشروعي الآن</span><h1>{state.profile.activityName}</h1><p>بيانات محلية للطلبات والمسودات. تظهر الأرقام المالية فقط بعد تسجيل أحداثها.</p></div><section className="micro-decision-surface" data-tone={priorityTone} aria-labelledby="home-priority"><span className="micro-overline">الفعل التالي</span><h2 id="home-priority">{state.followUp.title}</h2><p>{state.followUp.truth}</p><p className="micro-decision-next">{state.followUp.nextAction}</p><button className="micro-button micro-button-primary micro-button-block" type="button" onClick={() => navigate(state.followUp.href)}>{state.followUp.actionLabel}<ArrowLeft aria-hidden="true" /></button><div className="micro-home-links"><button className="micro-text-action" type="button" onClick={() => navigate("/schedule")}>فتح جدول المواعيد <ArrowLeft aria-hidden="true" /></button><button className="micro-text-action" type="button" onClick={() => navigate("/finance")}>فتح وضعي المالي <ArrowLeft aria-hidden="true" /></button></div></section><section className="micro-financial-pulse" aria-labelledby="pulse-title"><div className="micro-financial-pulse-heading"><div><span className="micro-overline">صورة الطلبات المسجلة</span><h2 id="pulse-title">متابعة مالية محدودة</h2></div><span>د.أ</span></div><dl><div><dt>قبض مسجل من الطلبات</dt><dd className="micro-number">{amount.format(state.pulse.registeredCollectionsMinor / 100)}</dd><small>ليس كاش المشروع</small></div><div><dt>دين مسجل بعد التسليم</dt><dd className="micro-number">{amount.format(state.pulse.registeredDebtMinor / 100)}</dd><small>مستحق عند العملاء</small></div><div><dt>طلبات قيد المتابعة</dt><dd className="micro-number">{count.format(state.pulse.activeOrderCount)}</dd><small>حالة تشغيلية</small></div><div><dt>نتائج مكتملة المعرفة</dt><dd className="micro-number">{count.format(state.pulse.finalResultOrderCount)}</dd><small>طلبات، لا ربح مشروع</small></div></dl></section><section className="micro-scope-line"><ClipboardPenLine aria-hidden="true" /><p>يقتصر الملخص على أحداث الطلبات المحلية. لا يحسب مصاريف عامة أو مخزونًا أو كاشًا أو ربحًا للمشروع كاملًا.</p><button className="micro-text-action" type="button" onClick={() => navigate("/review")}>فتح المراجعة <ArrowLeft aria-hidden="true" /></button></section></section>;
}
