/** Home is a local decision surface: one truthful next action from stored orders or drafts, never a fabricated dashboard KPI. */
import { ArrowLeft, ClipboardPenLine, Landmark, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import { InfoCard } from "@/components/presentation/InfoCard";
import type { ActivityProfile, OrderDraft, StoredCraftOrder } from "@/storage/local/types";

type HomeState = { phase: "loading" } | { phase: "error" } | { phase: "ready"; profile: ActivityProfile; drafts: readonly OrderDraft[]; orders: readonly StoredCraftOrder[] };
const money = new Intl.NumberFormat("ar-JO", { style: "currency", currency: "JOD", minimumFractionDigits: 2 });

export default function Home() {
  const [, navigate] = useLocation(); const { profiles, drafts, agreements, dataVersion } = usePrototypeServices(); const [state, setState] = useState<HomeState>({ phase: "loading" });
  useEffect(() => { let active = true; Promise.all([profiles.load(), drafts.list(), agreements.list()]).then(([profile, orderDrafts, orderList]) => { if (!active) return; if (!profile.ok || !orderDrafts.ok || !orderList.ok || !profile.value) { setState({ phase: "error" }); return; } setState({ phase: "ready", profile: profile.value, drafts: orderDrafts.value.filter(draft => !draft.linkedOrderId), orders: orderList.orders }); }); return () => { active = false; }; }, [agreements, dataVersion, drafts, profiles]);
  if (state.phase === "loading") return <div className="micro-route-loading" role="status">جارٍ ترتيب صورة مشروعك…</div>;
  if (state.phase === "error") return <section className="micro-page micro-not-found"><h1>تعذر تحميل صورة المشروع</h1><p>لم يتم تغيير بياناتك. أعد فتح التطبيق للمحاولة.</p></section>;
  const priorityOrder = state.orders.find(stored => stored.order.status !== "settled"); const latestDraft = state.drafts[0];
  const priorityTitle = priorityOrder ? `${priorityOrder.order.itemName}: ${priorityOrder.order.nextAction}` : latestDraft ? `أكمل مسودة: ${latestDraft.itemName || "وصف القطعة"}` : "ابدأ بطلب واحد تعرف تفاصيله";
  const priorityTruth = priorityOrder ? priorityOrder.order.settlementStatus === "debt" ? `المتبقي ${money.format(priorityOrder.order.receivableMinor / 100)} مسجل دينًا، ولم يزد الكاش.` : `العربون المحصل ${money.format(priorityOrder.order.depositCollectedMinor / 100)} · المتبقي ${money.format(priorityOrder.order.receivableMinor / 100)}.` : latestDraft ? "لديك مسودة محفوظة محليًا، من دون تكلفة أو اتفاق بعد." : "لا توجد طلبات أو مسودات محفوظة بعد.";
  const actionHref = priorityOrder ? `/orders/${priorityOrder.id}` : latestDraft ? `/orders/draft/${latestDraft.id}` : "/orders/new";
  const actionLabel = priorityOrder ? "فتح الطلب" : latestDraft ? "استئناف المسودة" : "ابدأ طلبًا مخصصًا";
  const hasOrders = state.orders.length > 0;
  return <section className="micro-page"><section className="micro-priority-panel" aria-labelledby="today-title"><img className="micro-priority-texture" src="/manus-storage/micro-onboarding-hero_24586879.png" alt="" /><div className="micro-priority-content"><span className="micro-eyebrow"><Sparkles aria-hidden="true" /> الأولوية الآن</span><h1 id="today-title">{priorityTitle}</h1><div className="micro-priority-truth"><span>ما نعرفه الآن</span><strong>{priorityTruth}</strong></div><p>{priorityOrder ? "الخطوة التالية مأخوذة من حالة الطلب، ولا تسجل أي حركة حتى تختار الفعل المناسب." : latestDraft ? "الخطوة التالية: راجع الوصف والكمية، ثم احفظ لتكمل لاحقًا." : "الخطوة التالية: أنشئ مسودة محلية قبل تكلفة أو سعر أو اتفاق."}</p><button className="micro-button micro-button-primary" type="button" onClick={() => navigate(actionHref)}>{actionLabel}<ArrowLeft aria-hidden="true" /></button></div></section><section className="micro-section" aria-labelledby="now-status-title"><div className="micro-section-heading"><div><span className="micro-overline">صورة اليوم</span><h2 id="now-status-title">{state.profile.activityName}</h2></div><span className="micro-status-chip">محلي على هذا الجهاز</span></div><InfoCard title={priorityOrder ? "هناك طلب يحتاج قرارًا" : latestDraft ? "هناك مسودة تنتظرك" : "لا توجد طلبات مسجلة بعد"} eyebrow="الحالة المحلية"><p>{priorityOrder ? `الفعل التالي: ${priorityOrder.order.nextAction}` : latestDraft ? "لم تُنشئ هذه المسودة أي مبلغ أو حركة مالية. أكملها حين تعرف التفاصيل." : "ابدأ من الوصف والكمية؛ ستأتي التكلفة والاتفاق في مراحل منفصلة."}</p><button className="micro-text-action" type="button" onClick={() => navigate("/orders")}>فتح الطلبات <ClipboardPenLine aria-hidden="true" /></button></InfoCard></section><section className="micro-guidance-grid" aria-label="ما تعرفه Micro"><InfoCard title={hasOrders ? "حالة المبالغ المرتبطة" : "ما تم حفظه"} eyebrow="في هذه الدورة" tone="accent"><p>{hasOrders ? "العربون والتحصيل والدين تظهر منفصلة عن النتيجة. لا يُعامل الدين أو العربون كربح تلقائي." : "اسم النشاط والمسودات فقط. لا توجد تكلفة أو سعر أو عربون أو نتيجة طلب بعد."}</p></InfoCard><InfoCard title={priorityOrder?.order.settlementStatus === "debt" ? "متابعة الدين" : "الخطوة التالية"} eyebrow="قرار واحد واضح" tone="warning">{priorityOrder?.order.settlementStatus === "debt" ? <p><Landmark aria-hidden="true" /> الدين لا يزيد الكاش المحصل. يبقى هنا كمتابعة، لا كتسوية وهمية.</p> : <p>سنفصل التكلفة عن الاتفاق، ثم التسليم عن التحصيل والدين عن الكاش.</p>}</InfoCard></section></section>;
}
