/** Slice 3 order surface: shows agreement truth and the one allowed next action, without pretending delivery or result exists. */
import { ArrowRight, CalendarDays, CircleDollarSign, Hammer, Play } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation, useParams } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import type { StoredCraftOrder } from "@/storage/local/types";

const money = new Intl.NumberFormat("ar-JO", { style: "currency", currency: "JOD", minimumFractionDigits: 2 });
const statusLabel = { provisional_agreement: "اتفاق مبدئي", confirmed: "تم التأكيد", in_progress: "قيد التنفيذ", ready: "جاهز للتسليم", delivered: "تم التسليم", settled: "مغلق" } as const;
const eventLabel: Record<string, string> = { created: "إنشاء الطلب", status_changed: "تحديث الحالة", deposit_collected: "تسجيل العربون", collection_recorded: "تسجيل قبض", debt_registered: "تسجيل دين", specification_revised: "تعديل المواصفات", cancelled: "إلغاء", deposit_refunded: "رد العربون", deposit_retained: "تسوية العربون" };

export default function OrderDetail() {
  const params = useParams<{ id: string }>(); const [, navigate] = useLocation(); const { agreements, dataVersion, notifyDataChanged } = usePrototypeServices(); const [stored, setStored] = useState<StoredCraftOrder | null>(null); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [message, setMessage] = useState<string | null>(null); const [isStarting, setIsStarting] = useState(false);
  useEffect(() => { let active = true; agreements.get(params.id).then(result => { if (!active) return; if (!result.ok || !result.stored) { setState("error"); return; } setStored(result.stored); setState("ready"); }); return () => { active = false; }; }, [agreements, dataVersion, params.id]);
  if (state === "loading") return <div className="micro-route-loading" role="status">جارٍ فتح الطلب…</div>;
  if (state === "error" || !stored) return <section className="micro-page micro-not-found"><h1>الطلب غير متاح محليًا</h1><p>ارجع إلى قائمة الطلبات، ثم أعد المحاولة.</p><button className="micro-button micro-button-primary" type="button" onClick={() => navigate("/orders")}>الطلبات</button></section>;
  const { order } = stored; const label = statusLabel[order.status as keyof typeof statusLabel] ?? "يحتاج مراجعة";
  async function start() { if (!stored) return; setMessage(null); setIsStarting(true); const result = await agreements.startExecution(stored.id); setIsStarting(false); if (!result.ok) { setMessage(result.message); return; } setStored(result.stored); notifyDataChanged(); }
  return <section className="micro-page micro-order-page"><button className="micro-back-button" type="button" onClick={() => navigate("/orders")}><ArrowRight aria-hidden="true" /> الطلبات</button><div className="micro-page-heading"><span className="micro-overline">{label}</span><h1>{order.itemName}</h1><p>{order.customerName} · الكمية: {order.quantity}</p></div><section className="micro-decision-card"><span>الفعل التالي</span><strong>{order.nextAction}</strong><p>موعد التسليم: {stored.deliveryDate}</p></section><section className="micro-summary-grid"><div><span>السعر المتفق عليه</span><strong>{money.format(order.agreedPriceMinor / 100)}</strong></div><div><span>المتبقي عند التسليم</span><strong>{money.format(order.receivableMinor / 100)}</strong></div></section>{order.depositCollectedMinor > 0 ? <section className="micro-deposit-truth"><CircleDollarSign aria-hidden="true" /><span><b>عربون محصل: {money.format(order.depositCollectedMinor / 100)}</b><br />كاش مرتبط بالطلب، وليس ربحًا نهائيًا.</span></section> : <section className="micro-note-card"><span>العربون</span><p>لم يسجل عربون لهذا الطلب. هذا لا يغيّر حالة التسليم أو التحصيل لاحقًا.</p></section>}<section className="micro-form-card"><h2 className="micro-section-title">سجل الطلب</h2><div className="micro-event-list">{order.events.map(event => <div key={event.id}><span className="micro-event-dot" /><p><b>{eventLabel[event.type] ?? "تحديث الطلب"}</b><small>{new Date(event.createdAt).toLocaleString("ar-JO")}{event.amountMinor ? ` · ${money.format(event.amountMinor / 100)}` : ""}</small></p></div>)}</div></section>{message ? <p className="micro-field-error" role="alert">{message}</p> : null}{order.status === "provisional_agreement" ? <button className="micro-button micro-button-primary micro-save-cost" type="button" disabled={isStarting} onClick={start}><Play aria-hidden="true" />{isStarting ? "جارٍ بدء التنفيذ…" : "ابدأ التنفيذ"}</button> : null}{order.status === "in_progress" ? <section className="micro-note-card"><Hammer aria-hidden="true" /><p>التسليم والتحصيل والدين والنتيجة ستظهر في Slice 4. لم نسجل أي قبض أو ربح هنا.</p></section> : null}<section className="micro-note-card"><CalendarDays aria-hidden="true" /><p>الاتفاق مسجل محليًا على هذا الجهاز. لا توجد مزامنة أو مشاركة خارجية في Prototype.</p></section></section>;
}
