/** Slice 3 list: places active local agreements above pre-domain drafts and keeps each next action explicit. */
import { ClipboardCheck, ClipboardPlus, ChevronLeft } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import { DecisionPanel } from "@/components/presentation/DecisionPanel";
import type { OrderDraft, StoredCraftOrder } from "@/storage/local/types";

type OrdersState = { phase: "loading" } | { phase: "error" } | { phase: "ready"; drafts: readonly OrderDraft[]; orders: readonly StoredCraftOrder[] };
export default function Orders() {
  const [, navigate] = useLocation(); const { drafts, agreements, dataVersion } = usePrototypeServices(); const [state, setState] = useState<OrdersState>({ phase: "loading" });
  useEffect(() => { let active = true; Promise.all([drafts.list(), agreements.list()]).then(([draftResult, orderResult]) => { if (!active) return; if (!draftResult.ok || !orderResult.ok) { setState({ phase: "error" }); return; } setState({ phase: "ready", drafts: draftResult.value.filter(draft => !draft.linkedOrderId), orders: orderResult.orders }); }); return () => { active = false; }; }, [agreements, dataVersion, drafts]);
  if (state.phase === "loading") return <div className="micro-route-loading" role="status">جارٍ تحميل الطلبات المحلية…</div>;
  if (state.phase === "error") return <section className="micro-page micro-not-found"><h1>تعذر تحميل الطلبات</h1><p>لم يتم تغيير شيء. أعد فتح التطبيق للمحاولة.</p></section>;
  const activeOrder = state.orders.find(item => item.order.status === "provisional_agreement" || item.order.status === "in_progress"); const firstDraft = state.drafts[0];
  return <section className="micro-page"><div className="micro-page-heading"><span className="micro-overline">المتابعة</span><h1>الطلبات</h1><p>كل طلب يقودك إلى قرار واحد فقط، لا إلى لوحة مكتظة.</p></div><DecisionPanel label="الأولوية الآن" truth={activeOrder ? `${activeOrder.order.itemName}: ${activeOrder.order.nextAction}` : firstDraft ? `أكمل مسودة: ${firstDraft.itemName || "وصف القطعة"}.` : "لا توجد طلبات محفوظة بعد."} nextAction={activeOrder ? "افتح الطلب وسجل خطوة التنفيذ التالية." : firstDraft ? "افتح المسودة واحفظ ما تعرفه الآن." : "ابدأ مسودة طلب مخصص واحد."} tone="accent" />{state.orders.length > 0 ? <section className="micro-draft-list" aria-label="الاتفاقات المحلية">{state.orders.map(stored => <button className="micro-draft-row" type="button" key={stored.id} onClick={() => navigate(`/orders/${stored.id}`)}><span className="micro-draft-symbol"><ClipboardCheck aria-hidden="true" /></span><span><strong>{stored.order.itemName}</strong><small>{stored.order.status === "in_progress" ? "قيد التنفيذ" : "اتفاق مبدئي"} · المتبقي: {(stored.order.receivableMinor / 100).toFixed(2)} د.أ</small></span><ChevronLeft aria-hidden="true" /></button>)}</section> : null}{state.drafts.length === 0 && state.orders.length === 0 ? <section className="micro-empty-state" aria-labelledby="orders-empty-title"><span className="micro-empty-symbol"><ClipboardPlus aria-hidden="true" /></span><span className="micro-status-chip">لا توجد بيانات بعد</span><h2 id="orders-empty-title">ابدأ بطلب واحد تعرف قصته</h2><p>الوصف والكمية وما اتفقت عليه تكفي كبداية.</p><button className="micro-button micro-button-primary" type="button" onClick={() => navigate("/orders/new")}><ClipboardPlus aria-hidden="true" /> إنشاء طلب مخصص</button></section> : null}{state.drafts.length > 0 ? <section className="micro-draft-list" aria-label="المسودات المحلية">{state.drafts.map(draft => <button className="micro-draft-row" type="button" key={draft.id} onClick={() => navigate(`/orders/draft/${draft.id}`)}><span className="micro-draft-symbol"><ClipboardPlus aria-hidden="true" /></span><span><strong>{draft.itemName || "مسودة تحتاج وصفًا"}</strong><small>{draft.intent === "customer_order" ? "طلب من عميل" : "تصميم مخطط"} · الكمية: {draft.quantity}</small></span><ChevronLeft aria-hidden="true" /></button>)}</section> : null}{state.orders.length > 0 || state.drafts.length > 0 ? <button className="micro-button micro-button-secondary" type="button" onClick={() => navigate("/orders/new")}>إنشاء مسودة أخرى</button> : null}</section>;
}
