/** Style: Micro «مسار القرار» — phone-first RTL agenda; time is an operational cue, not a decorative calendar. */
import { ArrowLeft, CalendarClock, CalendarDays, ChevronLeft } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import type { ScheduleOverview, ScheduledOrder } from "@/application/scheduling/scheduleService";

type ScheduleState = { phase: "loading" } | { phase: "error" } | { phase: "ready"; overview: ScheduleOverview };
const orderStatus: Record<string, string> = { provisional_agreement: "اتفاق مبدئي", confirmed: "تم التأكيد", in_progress: "قيد التنفيذ", ready: "جاهز للتسليم", delivered: "تم التسليم", settled: "مغلق" };

export default function Schedule() {
  const [, navigate] = useLocation(); const { schedules, dataVersion } = usePrototypeServices(); const [state, setState] = useState<ScheduleState>({ phase: "loading" });
  useEffect(() => { let active = true; schedules.overview().then((result) => { if (!active) return; if (!result.ok) { setState({ phase: "error" }); return; } setState({ phase: "ready", overview: result.value }); }); return () => { active = false; }; }, [dataVersion, schedules]);
  if (state.phase === "loading") return <div className="micro-route-loading" role="status">جارٍ تجهيز قائمة المواعيد…</div>;
  if (state.phase === "error") return <section className="micro-page micro-not-found"><h1>تعذر تحميل جدول المواعيد</h1><p>لم يتم تغيير أي موعد. أعد فتح التطبيق للمحاولة.</p><button className="micro-button micro-button-primary" type="button" onClick={() => navigate("/orders")}>الطلبات</button></section>;
  const total = state.overview.overdue.length + state.overview.today.length + state.overview.upcoming.length;
  return <section className="micro-page micro-schedule-page"><button className="micro-back-button" type="button" onClick={() => navigate("/")}><ArrowLeft aria-hidden="true" /> مشروعي الآن</button><div className="micro-page-heading"><span className="micro-overline">التنظيم التشغيلي</span><h1>جدول المواعيد</h1><p>يعرض مواعيد الطلبات المحلية التي تحتاج متابعة. لا يرسل تذكيرًا خارجيًا في هذا الإصدار.</p></div>{state.overview.overdue.length > 0 ? <ScheduleSection title="متأخر" description="هذه الطلبات تجاوزت موعدها المسجل وتحتاج قرارًا." tone="warning" items={state.overview.overdue} onOpen={(item) => navigate(`/schedule/${item.schedule.id}`)} /> : null}{state.overview.today.length > 0 ? <ScheduleSection title="اليوم" description="طلبات موعدها اليوم حسب توقيت عمّان." tone="accent" items={state.overview.today} onOpen={(item) => navigate(`/schedule/${item.schedule.id}`)} /> : null}{state.overview.upcoming.length > 0 ? <ScheduleSection title="قادم" description="رتب العمل القادم قبل أن يصبح متأخرًا." tone="support" items={state.overview.upcoming} onOpen={(item) => navigate(`/schedule/${item.schedule.id}`)} /> : null}{total === 0 ? <section className="micro-empty-state"><span className="micro-empty-symbol"><CalendarDays aria-hidden="true" /></span><span className="micro-status-chip">لا توجد مواعيد تشغيلية</span><h2>لا توجد طلبات تحتاج موعدًا الآن</h2><p>عند تثبيت اتفاق جديد ينشئ Micro موعد تسليم محليًا قابلًا للمتابعة.</p><button className="micro-button micro-button-primary" type="button" onClick={() => navigate("/orders/new")}>بدء طلب</button></section> : null}{state.overview.completedOrClosed > 0 ? <p className="micro-schedule-closed-note">يوجد {state.overview.completedOrClosed} موعدًا لطلبات أغلقت أو لم تعد تحتاج متابعة تشغيلية.</p> : null}</section>;
}

function ScheduleSection({ title, description, tone, items, onOpen }: { title: string; description: string; tone: "warning" | "accent" | "support"; items: readonly ScheduledOrder[]; onOpen: (item: ScheduledOrder) => void }) {
  return <section className="micro-schedule-section" data-tone={tone} aria-label={title}><div className="micro-schedule-heading"><div><span className="micro-overline">{title}</span><h2>{description}</h2></div><span>{items.length}</span></div><div className="micro-draft-list">{items.map((item) => <button className="micro-draft-row" type="button" key={item.schedule.id} onClick={() => onOpen(item)}><span className="micro-draft-symbol"><CalendarClock aria-hidden="true" /></span><span><strong>{item.order.order.itemName}</strong><small>{orderStatus[item.order.order.status] ?? "يحتاج مراجعة"} · الموعد: {item.schedule.scheduledFor}</small><small className="micro-row-next-action">الفعل التالي: {item.order.order.nextAction}</small></span><ChevronLeft aria-hidden="true" /></button>)}</div></section>;
}
