/** Style: Micro «مسار القرار» — one full-page RTL edit flow for an operational postponement with reason and preserved history. */
import { ArrowRight, CalendarClock, History } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation, useParams } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import type { ScheduleEntry } from "@/storage/local/types";

type EditorState = "loading" | "ready" | "error";
const eventLabel: Record<string, string> = { created: "تسجيل الموعد", postponed: "تأجيل الموعد", completed: "إكمال الموعد", cancelled: "إلغاء الموعد" };

export default function ScheduleEditor() {
  const { id } = useParams<{ id: string }>(); const [, navigate] = useLocation(); const { schedules, notifyDataChanged, dataVersion } = usePrototypeServices(); const [phase, setPhase] = useState<EditorState>("loading"); const [schedule, setSchedule] = useState<ScheduleEntry | null>(null); const [date, setDate] = useState(""); const [reason, setReason] = useState(""); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; schedules.get(id).then((result) => { if (!active) return; if (!result.ok) { setPhase("error"); return; } setSchedule(result.value); setDate(result.value.scheduledFor); setPhase("ready"); }); return () => { active = false; }; }, [dataVersion, id, schedules]);
  if (phase === "loading") return <div className="micro-route-loading" role="status">جارٍ فتح الموعد…</div>;
  if (phase === "error" || !schedule) return <section className="micro-page micro-not-found"><h1>الموعد غير متاح محليًا</h1><p>ارجع إلى جدول المواعيد وأعد المحاولة.</p><button className="micro-button micro-button-primary" type="button" onClick={() => navigate("/schedule")}>جدول المواعيد</button></section>;
  async function postpone() { if (!schedule) return; setMessage(null); setSaving(true); const result = await schedules.postpone(schedule.id, date, reason); setSaving(false); if (!result.ok) { setMessage(result.message); return; } setSchedule(result.value); setDate(result.value.scheduledFor); setReason(""); notifyDataChanged(); setMessage("تم حفظ التأجيل محليًا مع سبب وتاريخ الموعد السابق."); }
  return <section className="micro-page micro-schedule-page"><button className="micro-back-button" type="button" onClick={() => navigate("/schedule")}><ArrowRight aria-hidden="true" /> جدول المواعيد</button><div className="micro-page-heading"><span className="micro-overline">تعديل تشغيلي</span><h1>تأجيل موعد</h1><p>لا يغير التأجيل حالة الطلب أو السعر أو القبض أو الدين. إنه يسجل سببًا وتشغيلًا زمنيًا فقط.</p></div><section className="micro-decision-card"><span>الموعد المسجل</span><strong>{schedule.scheduledFor}</strong><p>{schedule.status === "postponed" ? `سبب التأجيل الأخير: ${schedule.postponeReason}` : "الموعد ما زال كما ثبت عند الاتفاق."}</p></section><section className="micro-form-card"><label className="micro-field"><span>الموعد الجديد</span><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="micro-field"><span>سبب التأجيل</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="مثال: تأخر تأكيد العميل" /></label>{message ? <p className={message.startsWith("تم ") ? "micro-save-note" : "micro-field-error"} role="status">{message}</p> : null}<button className="micro-button micro-button-primary micro-save-cost" type="button" disabled={saving} onClick={postpone}><CalendarClock aria-hidden="true" />{saving ? "جارٍ حفظ التأجيل…" : "حفظ التأجيل"}</button></section><section className="micro-form-card"><h2 className="micro-section-title"><History aria-hidden="true" /> سجل الموعد</h2><div className="micro-event-list">{schedule.events.map((event) => <div key={event.id}><span className="micro-event-dot" /><p><b>{eventLabel[event.type] ?? "تحديث الموعد"}</b><small>{event.scheduledFor}{event.previousScheduledFor ? ` · كان: ${event.previousScheduledFor}` : ""}{event.reason ? ` · ${event.reason}` : ""}</small></p></div>)}</div></section></section>;
}
