/** Local protection surface: it never claims cloud backup; import validates first and needs explicit replacement confirmation. */
import { Download, FileCheck2, MoonStar, Shield, Upload } from "lucide-react";
import { type ChangeEvent, useRef, useState } from "react";
import { useLocation } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import type { TransferPreview } from "@/application/transfers/localTransferService";
import { DecisionPanel } from "@/components/presentation/DecisionPanel";
import { useTheme } from "@/contexts/ThemeContext";

export default function SettingsPage() {
  const { theme, preference, toggleTheme } = useTheme(); const [, navigate] = useLocation(); const { transfers, notifyDataChanged } = usePrototypeServices(); const inputRef = useRef<HTMLInputElement>(null);
  const [preview, setPreview] = useState<TransferPreview | null>(null); const [notice, setNotice] = useState<string | null>(null); const [isWorking, setIsWorking] = useState(false);
  async function exportLocal() { setNotice(null); setIsWorking(true); const result = await transfers.createExport(); setIsWorking(false); if (!result.ok) { setNotice(result.message); return; } const blob = new Blob([JSON.stringify(result.value, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `micro-local-${result.value.exportedAt.slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); setNotice("تم تجهيز ملف تصدير محلي. احتفظ به في مكان تختاره؛ لا توجد نسخة سحابية هنا."); }
  async function chooseImport(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setNotice(null); setIsWorking(true); try { const prepared = transfers.prepareImport(await file.text()); if (!prepared.ok) { setNotice(prepared.message); return; } setPreview(prepared.value); } catch { setNotice("تعذر قراءة الملف. بقيت بيانات هذا الجهاز دون تغيير."); } finally { setIsWorking(false); } }
  async function confirmImport() { if (!preview) return; setNotice(null); setIsWorking(true); const result = await transfers.confirmImport(preview); setIsWorking(false); if (!result.ok) { setNotice(result.message); return; } setPreview(null); notifyDataChanged(); setNotice("تم استبدال البيانات المحلية بالملف الذي راجعته."); if (!result.value.profile) navigate("/setup"); }
  return <section className="micro-page"><div className="micro-page-heading"><span className="micro-overline">التحكم المحلي</span><h1>الإعدادات</h1><p>خيارات الواجهة وحماية البيانات على هذا الجهاز.</p></div><DecisionPanel label="الحالة الآن" truth="بيانات Prototype محلية فقط." nextAction="صدّر ملفًا قبل تغيير الجهاز أو الاستيراد فوق بياناتك الحالية." tone="support" /><section className="micro-settings-list" aria-label="إعدادات الواجهة والبيانات"><article className="micro-setting-row"><span className="micro-setting-icon"><MoonStar aria-hidden="true" /></span><div><h2>المظهر</h2><p>المعروض الآن: {theme === "dark" ? "داكن" : "فاتح"}، والافتراضي عند البداية: {preference === "system" ? "النظام" : "اختيارك المحلي"}.</p></div><button className="micro-button micro-button-secondary" type="button" onClick={toggleTheme}>تبديل</button></article><article className="micro-setting-row"><span className="micro-setting-icon"><Shield aria-hidden="true" /></span><div><h2>بياناتك على هذا الجهاز</h2><p>لا توجد مزامنة سحابية أو تسجيل دخول أو نسخة احتياطية تلقائية هنا.</p></div></article><StorageRow icon={Download} title="تصدير محلي" text="ينشئ ملف JSON لبيانات Prototype الحالية دون أسرار أو مفاتيح." label="تصدير البيانات المحلية" disabled={isWorking} onClick={exportLocal} /><StorageRow icon={Upload} title="استيراد محلي" text="نقرأ الملف ونتحقق منه أولًا، ثم نعرض ملخصًا قبل استبدال أي بيانات." label="اختيار ملف استيراد" disabled={isWorking} onClick={() => inputRef.current?.click()} /><input ref={inputRef} className="micro-visually-hidden" type="file" accept="application/json,.json" onChange={chooseImport} />{preview ? <section className="micro-import-preview" aria-live="polite"><span className="micro-overline"><FileCheck2 aria-hidden="true" /> ملف جاهز للمراجعة</span><h2>لم نغير بياناتك بعد</h2><p>الملف صادر في {new Date(preview.summary.exportedAt).toLocaleString("ar-JO")} ويحتوي على:</p><ul><li>{preview.summary.profile ? "ملف نشاط واحد" : "لا يحتوي ملف نشاط"}</li><li>{preview.summary.preferences ? "تفضيل مظهر محفوظ" : "لا يحتوي تفضيل مظهر محفوظ"}</li><li>{preview.summary.drafts} مسودة</li><li>{preview.summary.orders} طلب</li><li>{preview.summary.schedules} موعد</li><li>{preview.summary.snapshots} Snapshot تكلفة و{preview.summary.events} حدث</li></ul><p className="micro-field-error">التأكيد سيستبدل البيانات المحلية الحالية بهذا الملف. لا توجد استعادة تلقائية بعد الضغط.</p><div className="micro-form-actions"><button className="micro-button micro-button-secondary" type="button" disabled={isWorking} onClick={() => setPreview(null)}>إلغاء</button><button className="micro-button micro-button-primary" type="button" disabled={isWorking} onClick={confirmImport}>{isWorking ? "جارٍ الاستيراد…" : "استبدال البيانات المحلية"}</button></div></section> : null}{notice ? <p className="micro-save-note" role="status">{notice}</p> : null}</section></section>;
}

function StorageRow({ icon: Icon, title, text, label, disabled, onClick }: { icon: typeof Download; title: string; text: string; label: string; disabled: boolean; onClick: () => void }) {
  return <article className="micro-setting-row"><span className="micro-setting-icon"><Icon aria-hidden="true" /></span><div><h2>{title}</h2><p>{text}</p></div><button className="micro-icon-button" type="button" disabled={disabled} onClick={onClick} aria-label={label}><Icon aria-hidden="true" /></button></article>;
}
