/** Style: Micro «مسار القرار» — supplier purchases are operational facts, never disguised as expense or inventory. */
import { ArrowLeft, Plus, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { usePrototypeServices } from "@/app/PrototypeServicesContext";
import type { SupplierPurchase } from "@micro-domain/supplier-purchase/index.js";
import type { SupplierPurchaseSummary } from "@/application/suppliers/supplierPurchaseService";

type PageState = { phase: "loading" } | { phase: "error" } | { phase: "ready"; purchases: readonly SupplierPurchase[]; summary: SupplierPurchaseSummary };
const money = new Intl.NumberFormat("en-JO", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function Suppliers() {
  const [, navigate] = useLocation(); const { supplierPurchases, dataVersion } = usePrototypeServices(); const [state, setState] = useState<PageState>({ phase: "loading" });
  useEffect(() => { let active = true; Promise.all([supplierPurchases.list(), supplierPurchases.readSummary()]).then(([purchases, summary]) => { if (!active) return; if (!purchases.ok || !summary.ok) { setState({ phase: "error" }); return; } setState({ phase: "ready", purchases: purchases.value, summary: summary.value }); }); return () => { active = false; }; }, [dataVersion, supplierPurchases]);
  if (state.phase === "loading") return <div className="micro-route-loading" role="status">جارٍ قراءة شراء المواد المحلي…</div>;
  if (state.phase === "error") return <section className="micro-page micro-not-found"><h1>تعذر قراءة مشتريات الموردين</h1><p>لم يتم تغيير أي سجل. أعد فتح التطبيق للمحاولة.</p><button className="micro-button micro-button-primary" type="button" onClick={() => navigate("/finance")}>الوضع المالي</button></section>;
  const open = state.purchases.filter((purchase) => purchase.payableMinor > 0);
  return <section className="micro-page micro-finance-page"><button className="micro-back-button" type="button" onClick={() => navigate("/finance")}><ArrowLeft aria-hidden="true" /> الوضع المالي</button><div className="micro-page-heading"><span className="micro-overline">مواد وموردون</span><h1>مشتريات المواد</h1><p>سجل ما اشتريته للمشروع وما دُفع وما بقي. شراء المواد ليس مصروف بيع أو مخزونًا جاهزًا بعد.</p></div><section className="micro-decision-card"><WalletCards aria-hidden="true" /><div><span>ما عليك للموردين من شراء مواد</span><strong className="micro-number">{money.format(state.summary.supplierPayablesMinor / 100)} د.أ</strong><p>{state.summary.truth}</p></div></section><button className="micro-button micro-button-primary micro-full-action" type="button" onClick={() => navigate("/suppliers/purchase/new")}><Plus aria-hidden="true" /> سجل شراء مواد</button><section className="micro-supplier-list"><div className="micro-finance-event-heading"><span className="micro-overline">المشتريات المفتوحة</span><h2>{open.length ? `${open.length} شراء يحتاج متابعة` : "لا توجد مشتريات مفتوحة"}</h2></div>{open.length ? open.map((purchase) => <article key={purchase.id}><div><strong>{purchase.supplierName}</strong><small>{purchase.purchasedOn} · {purchase.note}</small>{purchase.dueOn ? <small>الاستحقاق: {purchase.dueOn}</small> : <small>لا يوجد تاريخ استحقاق مسجل</small>}</div><div className="micro-supplier-balance"><b className="micro-number">المتبقي {money.format(purchase.payableMinor / 100)} د.أ</b><button className="micro-button micro-button-secondary" type="button" onClick={() => navigate(`/suppliers/purchase/${purchase.id}/payment`)}>سجل دفعة</button></div></article>) : <p>لا تسجل شراء مواد كمصروف تشغيل. عند الشراء من مورد ابدأ من هذا السجل حتى يظهر الكاش والمتبقي بصدق.</p>}</section>{state.purchases.length > open.length ? <section className="micro-supplier-list micro-supplier-settled"><div className="micro-finance-event-heading"><span className="micro-overline">مكتملة الدفع</span><h2>آخر المشتريات المسددة</h2></div>{state.purchases.filter((purchase) => purchase.payableMinor === 0).slice(0, 4).map((purchase) => <article key={purchase.id}><div><strong>{purchase.supplierName}</strong><small>{purchase.purchasedOn} · {purchase.note}</small></div><b className="micro-number">{money.format(purchase.totalMinor / 100)} د.أ</b></article>)}</section> : null}</section>;
}
