/** Slice 5 transfer boundary: parse and validate first; only an explicit confirmation may replace local IndexedDB state. */
import { localExportFormat, localExportVersion, localProfileId, localSchemaVersion, type LocalExportFile, type LocalStoreSnapshot, type PrototypeLocalStore } from "@/storage/local/types";

export type TransferSummary = { profile: boolean; preferences: boolean; drafts: number; orders: number; schedules: number; recurrences: number; financialEvents: number; supplierPurchases: number; cashWallets: number; cashContinuityEntries: number; materials: number; inventoryMovements: number; catalogItems: number; shortCashDeclarations: number; snapshots: number; events: number; exportedAt: string };
export type TransferPreview = { file: LocalExportFile; summary: TransferSummary };
export type TransferResult<T> = { ok: true; value: T } | { ok: false; code: "validation_error" | "storage_error"; message: string };
const fail = <T,>(message: string): TransferResult<T> => ({ ok: false, code: "validation_error", message });
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);
const isString = (value: unknown): value is string => typeof value === "string";
const isDate = (value: unknown): value is string => isString(value) && !Number.isNaN(Date.parse(value));
const isMoney = (value: unknown): value is number => typeof value === "number" && Number.isInteger(value) && value >= 0;
const isPositiveQuantity = (value: unknown): value is number => typeof value === "number" && Number.isFinite(value) && value > 0;
const isKnownState = (value: unknown) => value === "known" || value === "estimated" || value === "incomplete" || value === "variable" || value === "stale" || value === "partial";
const isResultStatus = (value: unknown) => value === "final" || value === "estimated" || value === "incomplete" || value === "review_required";
const isOrderStatus = (value: unknown) => typeof value === "string" && ["draft", "provisional_agreement", "confirmed", "in_progress", "ready", "delivered", "settled", "postponed", "cancelled", "needs_review"].includes(value);
const isSettlement = (value: unknown) => typeof value === "string" && ["unpaid", "partially_paid", "paid", "debt", "cancelled", "cancelled_pending", "cancelled_refunded", "cancelled_retained"].includes(value);
const isScheduleStatus = (value: unknown) => value === "scheduled" || value === "postponed" || value === "completed" || value === "cancelled";
const isScheduleTime = (value: unknown): value is string => isString(value) && /^([01]\d|2[0-3]):[0-5]\d$/.test(value);
const isScheduleDuration = (value: unknown): value is number => typeof value === "number" && Number.isInteger(value) && value >= 15 && value <= 720 && value % 15 === 0;
const isRecurrenceFrequency = (value: unknown) => value === "weekly" || value === "monthly";
const isRecurrenceStatus = (value: unknown) => value === "active" || value === "cancelled";
const isFollowUpEvent = (value: unknown) => isRecord(value) && isString(value.id) && (value.type === "created" || value.type === "changed") && isString(value.idempotencyKey) && value.idempotencyKey.trim().length > 0 && isDate(value.createdAt) && (value.previousDate === null || isString(value.previousDate)) && (value.followUpDate === null || isString(value.followUpDate)) && isString(value.reason) && value.reason.trim().length > 0;
const isRecurrence = (value: unknown) => isRecord(value) && isString(value.id) && isString(value.sourceScheduleId) && isString(value.orderId) && isRecurrenceFrequency(value.frequency) && typeof value.occurrenceCount === "number" && Number.isInteger(value.occurrenceCount) && value.occurrenceCount >= 1 && value.occurrenceCount <= 12 && isRecurrenceStatus(value.status) && isString(value.idempotencyKey) && value.idempotencyKey.trim().length > 0 && (value.cancelledAt === null || isDate(value.cancelledAt)) && (value.cancellationReason === null || (isString(value.cancellationReason) && value.cancellationReason.trim().length > 0)) && isDate(value.createdAt) && isDate(value.updatedAt) && (value.status === "active" ? value.cancelledAt === null && value.cancellationReason === null : value.cancelledAt !== null && value.cancellationReason !== null);
const isScheduleEvent = (value: unknown) => isRecord(value) && isString(value.id) && isString(value.idempotencyKey) && isDate(value.createdAt) && (value.type === "created" || value.type === "postponed" || value.type === "timing_changed" || value.type === "completed" || value.type === "cancelled") && (value.previousScheduledFor === null || isString(value.previousScheduledFor)) && isString(value.scheduledFor) && (value.previousScheduledTime === null || isScheduleTime(value.previousScheduledTime)) && (value.scheduledTime === null || isScheduleTime(value.scheduledTime)) && (value.previousDurationMinutes === null || isScheduleDuration(value.previousDurationMinutes)) && (value.durationMinutes === null || isScheduleDuration(value.durationMinutes)) && (value.reason === null || isString(value.reason));
const isFinancialType = (value: unknown) => value === "owner_investment_cash" || value === "owner_withdrawal_cash" || value === "operating_expense_cash" || value === "operating_expense_payable" || value === "payable_settlement_cash";
const isSignedMoney = (value: unknown) => typeof value === "number" && Number.isInteger(value);
const isSharedProjectShare = (value: unknown, knowledge: unknown) => value === undefined || value === null || (isRecord(value) && (value.basis === "agreed_fixed_share" || value.basis === "owner_estimate" || value.basis === "needs_review") && (value.note === null || isString(value.note)) && (value.basis === "agreed_fixed_share" ? knowledge === "known" : value.basis === "owner_estimate" ? knowledge === "estimated" : knowledge === "needs_review"));
const isExpenseContext = (value: unknown) => isRecord(value) && (value.relationship === "project" || value.relationship === "shared") && (value.behavior === "fixed" || value.behavior === "variable" || value.behavior === "mixed" || value.behavior === "unknown") && (value.purpose === "project_general" || value.purpose === "period" || value.purpose === "order" || value.purpose === "product" || value.purpose === "campaign" || value.purpose === "unallocated") && (value.knowledge === "known" || value.knowledge === "estimated" || value.knowledge === "needs_review") && (value.relationship === "shared" ? isSharedProjectShare(value.sharedProjectShare, value.knowledge) : value.sharedProjectShare === undefined || value.sharedProjectShare === null);
function validFinancialEvent(value: unknown): boolean { if (!isRecord(value) || !isString(value.id) || !isFinancialType(value.type) || value.currency !== "JOD" || !isMoney(value.amountMinor) || value.amountMinor === 0 || !isString(value.occurredOn) || !isDate(`${value.occurredOn}T12:00:00.000Z`) || !isDate(value.recordedAt) || !isString(value.idempotencyKey) || !isString(value.note) || !(value.counterparty === null || isString(value.counterparty)) || !(value.relatedEventId === null || isString(value.relatedEventId)) || !isSignedMoney(value.cashDeltaMinor) || !isSignedMoney(value.payableDeltaMinor) || !isSignedMoney(value.ownerCapitalDeltaMinor) || !isSignedMoney(value.operatingExpenseDeltaMinor)) return false; const expenseContext = value.expenseContext; const hasExpenseContext = expenseContext !== undefined && expenseContext !== null; if (hasExpenseContext && (!isExpenseContext(expenseContext) || (value.type !== "operating_expense_cash" && value.type !== "operating_expense_payable"))) return false; const amount = value.amountMinor; const expected = value.type === "owner_investment_cash" ? [amount, 0, amount, 0] : value.type === "owner_withdrawal_cash" ? [-amount, 0, -amount, 0] : value.type === "operating_expense_cash" ? [-amount, 0, 0, amount] : value.type === "operating_expense_payable" ? [0, amount, 0, amount] : [-amount, -amount, 0, 0]; return value.cashDeltaMinor === expected[0] && value.payableDeltaMinor === expected[1] && value.ownerCapitalDeltaMinor === expected[2] && value.operatingExpenseDeltaMinor === expected[3] && (value.type === "payable_settlement_cash" ? isString(value.relatedEventId) && value.relatedEventId.trim().length > 0 : value.relatedEventId === null); }
function validSupplierPurchase(value: unknown): boolean { if (!isRecord(value) || !isString(value.id) || !isString(value.supplierName) || !value.supplierName.trim() || !isString(value.note) || !value.note.trim() || !isString(value.purchasedOn) || !isDate(`${value.purchasedOn}T12:00:00.000Z`) || !(value.dueOn === null || isString(value.dueOn)) || (isString(value.dueOn) && !isDate(`${value.dueOn}T12:00:00.000Z`)) || !isMoney(value.totalMinor) || value.totalMinor === 0 || !isMoney(value.paidMinor) || !isMoney(value.payableMinor) || !isString(value.idempotencyKey) || !isDate(value.createdAt) || !isDate(value.updatedAt) || !Array.isArray(value.payments)) return false; const paymentKeys = new Set<string>(); const totalPaid = value.payments.reduce<number>((sum, payment) => { if (!isRecord(payment) || !isString(payment.id) || !isMoney(payment.amountMinor) || payment.amountMinor === 0 || !isString(payment.occurredOn) || !isDate(`${payment.occurredOn}T12:00:00.000Z`) || !isDate(payment.recordedAt) || !isString(payment.idempotencyKey) || !isString(payment.note) || !payment.note.trim() || paymentKeys.has(payment.idempotencyKey)) return Number.NaN; paymentKeys.add(payment.idempotencyKey); return sum + payment.amountMinor; }, 0); const status = totalPaid === 0 ? "unpaid" : totalPaid === value.totalMinor ? "paid" : "partially_paid"; return Number.isInteger(totalPaid) && totalPaid === value.paidMinor && value.payableMinor === value.totalMinor - totalPaid && value.status === status; }
const isCashWalletKind = (value: unknown) => value === "cash_drawer" || value === "bank_account" || value === "digital_wallet" || value === "other";
const isCashEntryType = (value: unknown) => value === "opening_balance" || value === "cash_adjustment" || value === "transfer_out" || value === "transfer_in" || value === "reversal";
function validCashWallet(value: unknown): boolean { return isRecord(value) && isString(value.id) && isString(value.name) && value.name.trim().length > 0 && isCashWalletKind(value.kind) && isDate(value.createdAt) && isString(value.createdOperationKey) && value.createdOperationKey.trim().length > 0; }
function validCashEntry(value: unknown): boolean { if (!isRecord(value) || !isString(value.id) || !isString(value.walletId) || !isCashEntryType(value.type) || !isString(value.occurredOn) || !isDate(`${value.occurredOn}T12:00:00.000Z`) || !isDate(value.recordedAt) || !isSignedMoney(value.cashDeltaMinor) || value.cashDeltaMinor === 0 || !isString(value.note) || !value.note.trim() || !(value.reason === null || isString(value.reason)) || !isString(value.operationKey) || !value.operationKey.trim() || !(value.transferId === null || isString(value.transferId)) || !(value.reversesEntryId === null || isString(value.reversesEntryId))) return false; const delta = value.cashDeltaMinor as number; if (value.type === "opening_balance" && delta < 0) return false; if (value.type === "cash_adjustment" && (!isString(value.reason) || !value.reason.trim())) return false; if ((value.type === "transfer_out" || value.type === "transfer_in") && (!isString(value.transferId) || value.reason !== null)) return false; return value.type === "reversal" ? isString(value.reason) && value.reason.trim().length > 0 && isString(value.reversesEntryId) : value.reversesEntryId === null; }
const isMaterialUnit = (value: unknown) => value === "piece" || value === "meter" || value === "kilogram" || value === "liter" || value === "other";
const isInventoryMovementType = (value: unknown) => value === "opening" || value === "purchase_receipt" || value === "consumption" || value === "waste" || value === "adjustment" || value === "reversal";
function validMaterial(value: unknown): boolean { return isRecord(value) && isString(value.id) && isString(value.name) && value.name.trim().length > 0 && isMaterialUnit(value.unit) && isDate(value.createdAt) && isString(value.createdOperationKey) && value.createdOperationKey.trim().length > 0; }
function validInventoryMovement(value: unknown): boolean { if (!isRecord(value) || !isString(value.id) || !isString(value.materialId) || !isInventoryMovementType(value.type) || !isString(value.occurredOn) || !isDate(`${value.occurredOn}T12:00:00.000Z`) || !isDate(value.recordedAt) || !isSignedMoney(value.quantityDeltaMilli) || !isSignedMoney(value.valueDeltaMinor) || value.quantityDeltaMilli === 0 || value.valueDeltaMinor === 0 || !isString(value.note) || !value.note.trim() || !(value.reason === null || isString(value.reason)) || !isString(value.operationKey) || !value.operationKey.trim() || !(value.purchaseId === null || isString(value.purchaseId)) || !(value.orderId === null || isString(value.orderId)) || !(value.reversesMovementId === null || isString(value.reversesMovementId))) return false; const quantity = value.quantityDeltaMilli as number; const amount = value.valueDeltaMinor as number; if ((value.type === "opening" || value.type === "purchase_receipt") && (quantity < 0 || amount < 0)) return false; if ((value.type === "consumption" || value.type === "waste") && (quantity > 0 || amount > 0)) return false; if (value.type === "purchase_receipt" ? !isString(value.purchaseId) : value.purchaseId !== null) return false; if (value.type === "consumption" ? !isString(value.orderId) : value.orderId !== null) return false; if (["waste", "adjustment", "reversal"].includes(value.type as string) && (!isString(value.reason) || !value.reason.trim())) return false; return value.type === "reversal" ? isString(value.reversesMovementId) : value.reversesMovementId === null; }
function validCatalogItem(value: unknown): boolean { return isRecord(value) && isString(value.id) && (value.kind === "product" || value.kind === "service") && isString(value.name) && value.name.trim().length > 0 && (value.unitLabel === null || isString(value.unitLabel)) && typeof value.active === "boolean" && isDate(value.createdAt) && isDate(value.updatedAt) && isString(value.createdOperationKey) && value.createdOperationKey.trim().length > 0; }
function validShortCashDeclaration(value: unknown): boolean { return isRecord(value) && isString(value.id) && (value.kind === "declaration" || value.kind === "reversal") && (value.direction === "collection" || value.direction === "commitment") && isMoney(value.amountMinor) && value.amountMinor > 0 && isString(value.dueOn) && isDate(`${value.dueOn}T12:00:00.000Z`) && isString(value.source) && value.source.trim().length > 0 && (value.knowledge === "known" || value.knowledge === "estimated" || value.knowledge === "needs_review") && isString(value.note) && value.note.trim().length > 0 && (value.relatedOrderId === null || isString(value.relatedOrderId)) && (value.relatedEventId === null || isString(value.relatedEventId)) && !(isString(value.relatedOrderId) && isString(value.relatedEventId)) && isString(value.idempotencyKey) && value.idempotencyKey.trim().length > 0 && (value.reversalOfId === null || isString(value.reversalOfId)) && isDate(value.createdAt) && (value.kind === "declaration" ? value.reversalOfId === null : isString(value.reversalOfId) && value.reversalOfId.trim().length > 0); }

function validDraftCostSnapshot(value: unknown): boolean {
  if (!isRecord(value) || !isString(value.id) || !Number.isInteger(value.revision) || !isDate(value.createdAt) || value.currency !== "JOD" || !isPositiveQuantity(value.quantity) || !Array.isArray(value.materialItems) || !isMoney(value.packagingMinor) || !isMoney(value.deliveryMinor) || !isMoney(value.wasteMinor) || !isMoney(value.safetyBufferMinor)) return false;
  if (!(value.time === null || (isRecord(value.time) && typeof value.time.minutes === "number" && isMoney(value.time.hourlyRateMinor) && (value.time.confidence === "known" || value.time.confidence === "estimated")))) return false;
  return value.materialItems.every(item => isRecord(item) && isString(item.name) && isString(item.unit) && isPositiveQuantity(item.quantity) && isMoney(item.unitPriceMinor) && (item.confidence === "known" || item.confidence === "estimated"));
}

function validDomainCostSnapshot(value: unknown): boolean {
  if (!isRecord(value) || !isString(value.id) || value.currency !== "JOD" || !isPositiveQuantity(value.quantity) || !isKnownState(value.knowledgeState) || !isDate(value.createdAt) || !isRecord(value.input)) return false;
  return ["materialCostMinor", "timeCostMinor", "packagingMinor", "deliveryMinor", "wasteMinor", "plannedCostMinor", "unitCostMinor", "priceFloorMinor"].every(key => isMoney(value[key]));
}

function validEvent(value: unknown): boolean {
  return isRecord(value) && isString(value.id) && isString(value.type) && isString(value.idempotencyKey) && isDate(value.createdAt);
}

function validateSnapshot(data: unknown): data is LocalStoreSnapshot {
  if (!isRecord(data) || !Array.isArray(data.drafts) || !Array.isArray(data.orders) || !Array.isArray(data.schedules) || !Array.isArray(data.recurrences) || !Array.isArray(data.financialEvents) || !Array.isArray(data.supplierPurchases) || !Array.isArray(data.cashWallets) || !Array.isArray(data.cashContinuityEntries) || !Array.isArray(data.materials) || !Array.isArray(data.inventoryMovements) || !Array.isArray(data.catalogItems) || !Array.isArray(data.shortCashDeclarations)) return false;
  if (data.profile !== null && (!isRecord(data.profile) || data.profile.id !== localProfileId || !isString(data.profile.activityName) || data.profile.currency !== "JOD" || data.profile.activityType !== "custom_craft" || !isDate(data.profile.createdAt) || !isDate(data.profile.updatedAt))) return false;
  if (data.preferences !== null && (!isRecord(data.preferences) || data.preferences.id !== "local-preferences" || !(data.preferences.theme === "light" || data.preferences.theme === "dark" || data.preferences.theme === "system") || !(data.preferences.dailyScheduleCapacityMinutes === null || isScheduleDuration(data.preferences.dailyScheduleCapacityMinutes)) || !isDate(data.preferences.updatedAt))) return false;
  const orderIds = new Set<string>();
  for (const stored of data.orders) {
    if (!isRecord(stored) || !isString(stored.id) || !isDate(stored.createdAt) || !isDate(stored.updatedAt) || !isString(stored.deliveryDate) || !(stored.catalogItemId === null || isString(stored.catalogItemId)) || !(stored.agreementSource === null || isString(stored.agreementSource)) || !(stored.followUpSummary === null || isString(stored.followUpSummary)) || !(stored.followUpDate === null || isString(stored.followUpDate)) || !(stored.followUpReason === null || isString(stored.followUpReason)) || !Array.isArray(stored.followUpEvents) || !stored.followUpEvents.every(isFollowUpEvent) || !isRecord(stored.order)) return false;
    const order = stored.order;
    if (order.id !== stored.id || !isString(order.customerName) || !isString(order.itemName) || !isString(order.specifications) || !isPositiveQuantity(order.quantity) || order.currency !== "JOD" || !isMoney(order.agreedPriceMinor) || !isMoney(order.depositCollectedMinor) || !isMoney(order.collectedMinor) || !isMoney(order.receivableMinor) || !isMoney(order.recognizedRevenueMinor) || !isMoney(order.recognizedCostMinor) || !(order.profitIndicatorMinor === null || isMoney(order.profitIndicatorMinor)) || !isOrderStatus(order.status) || !isSettlement(order.settlementStatus) || !isResultStatus(order.resultStatus) || !Array.isArray(order.events) || !order.events.every(validEvent) || !Array.isArray(order.costSnapshots) || !order.costSnapshots.every(validDomainCostSnapshot) || !validDomainCostSnapshot(order.costSnapshot)) return false;
    if (orderIds.has(stored.id)) return false; orderIds.add(stored.id);
  }
  const draftIds = new Set<string>();
  for (const draft of data.drafts) {
    if (!isRecord(draft) || !isString(draft.id) || !(draft.intent === "customer_order" || draft.intent === "planned_design") || !isString(draft.customerName) || !isString(draft.itemName) || !(draft.catalogItemId === null || isString(draft.catalogItemId)) || !isString(draft.specifications) || !isPositiveQuantity(draft.quantity) || !Array.isArray(draft.costSnapshots) || !draft.costSnapshots.every(validDraftCostSnapshot) || !(draft.activeCostSnapshotId === null || isString(draft.activeCostSnapshotId)) || !(draft.linkedOrderId === null || isString(draft.linkedOrderId)) || !isDate(draft.createdAt) || !isDate(draft.updatedAt)) return false;
    if (draftIds.has(draft.id) || (isString(draft.linkedOrderId) && !orderIds.has(draft.linkedOrderId))) return false; draftIds.add(draft.id);
  }
  const scheduleIds = new Set<string>();
  for (const schedule of data.schedules) {
    if (!isRecord(schedule) || !isString(schedule.id) || !isString(schedule.orderId) || schedule.kind !== "delivery" || !isString(schedule.scheduledFor) || !(schedule.scheduledTime === null || isScheduleTime(schedule.scheduledTime)) || !(schedule.durationMinutes === null || isScheduleDuration(schedule.durationMinutes)) || (schedule.scheduledTime === null) !== (schedule.durationMinutes === null) || !(schedule.recurrenceId === null || isString(schedule.recurrenceId)) || !(schedule.recurrenceIndex === null || (typeof schedule.recurrenceIndex === "number" && Number.isInteger(schedule.recurrenceIndex) && schedule.recurrenceIndex >= 1 && schedule.recurrenceIndex <= 12)) || (schedule.recurrenceId === null) !== (schedule.recurrenceIndex === null) || !isScheduleStatus(schedule.status) || !(schedule.postponeReason === null || isString(schedule.postponeReason)) || !isDate(schedule.createdAt) || !isDate(schedule.updatedAt) || !Array.isArray(schedule.events) || !schedule.events.every(isScheduleEvent) || !orderIds.has(schedule.orderId) || scheduleIds.has(schedule.id)) return false;
    scheduleIds.add(schedule.id);
  }
  const recurrenceIds = new Set<string>(); const recurrenceKeys = new Set<string>(); const appearanceKeys = new Set<string>();
  for (const recurrence of data.recurrences) {
    if (!isRecurrence(recurrence) || recurrenceIds.has(recurrence.id) || recurrenceKeys.has(recurrence.idempotencyKey) || !scheduleIds.has(recurrence.sourceScheduleId) || !orderIds.has(recurrence.orderId)) return false;
    const source = data.schedules.find(schedule => schedule.id === recurrence.sourceScheduleId);
    if (!source || source.orderId !== recurrence.orderId || source.recurrenceId !== null) return false;
    recurrenceIds.add(recurrence.id); recurrenceKeys.add(recurrence.idempotencyKey);
  }
  for (const schedule of data.schedules) {
    if (schedule.recurrenceId !== null) {
      if (!recurrenceIds.has(schedule.recurrenceId) || appearanceKeys.has(`${schedule.recurrenceId}:${schedule.recurrenceIndex}`)) return false;
      appearanceKeys.add(`${schedule.recurrenceId}:${schedule.recurrenceIndex}`);
    }
  }
  const financialIds = new Set<string>(); const financialKeys = new Set<string>();
  for (const event of data.financialEvents) {
    if (!validFinancialEvent(event) || financialIds.has(event.id) || financialKeys.has(`${event.type}:${event.idempotencyKey}`)) return false;
    financialIds.add(event.id); financialKeys.add(`${event.type}:${event.idempotencyKey}`);
  }
  const purchaseIds = new Set<string>(); const purchaseKeys = new Set<string>();
  for (const purchase of data.supplierPurchases ?? []) { if (!validSupplierPurchase(purchase) || purchaseIds.has(purchase.id) || purchaseKeys.has(purchase.idempotencyKey)) return false; purchaseIds.add(purchase.id); purchaseKeys.add(purchase.idempotencyKey); }
  const walletIds = new Set<string>(); const walletOperationKeys = new Set<string>();
  for (const wallet of data.cashWallets ?? []) { if (!validCashWallet(wallet) || walletIds.has(wallet.id) || walletOperationKeys.has(wallet.createdOperationKey)) return false; walletIds.add(wallet.id); walletOperationKeys.add(wallet.createdOperationKey); }
  const entryIds = new Set<string>(); const entryOperationKeys = new Set<string>(); const reversedIds = new Set<string>(); const transferGroups = new Map<string, Record<string, unknown>[]>();
  for (const entry of data.cashContinuityEntries ?? []) { if (!validCashEntry(entry) || entryIds.has(entry.id) || !walletIds.has(entry.walletId) || entryOperationKeys.has(entry.operationKey)) return false; entryIds.add(entry.id); entryOperationKeys.add(entry.operationKey); if (entry.type === "reversal") { if (reversedIds.has(entry.reversesEntryId)) return false; reversedIds.add(entry.reversesEntryId); } if (isString(entry.transferId)) transferGroups.set(entry.transferId, [...(transferGroups.get(entry.transferId) ?? []), entry]); }
  for (const entry of data.cashContinuityEntries ?? []) { if (entry.type === "reversal") { const original = (data.cashContinuityEntries ?? []).find((candidate) => candidate.id === entry.reversesEntryId); if (!original || entry.cashDeltaMinor !== -original.cashDeltaMinor) return false; } }
  for (const group of transferGroups.values()) { if (group.length !== 2 || group.reduce((sum, entry) => sum + (entry.cashDeltaMinor as number), 0) !== 0 || !group.some((entry) => entry.type === "transfer_out") || !group.some((entry) => entry.type === "transfer_in")) return false; }
  const materialIds = new Set<string>(); const materialKeys = new Set<string>();
  for (const material of data.materials) { if (!validMaterial(material) || materialIds.has(material.id) || materialKeys.has(material.createdOperationKey)) return false; materialIds.add(material.id); materialKeys.add(material.createdOperationKey); }
  const inventoryIds = new Set<string>(); const inventoryKeys = new Set<string>(); const reversedInventoryIds = new Set<string>();
  for (const movement of data.inventoryMovements) { if (!validInventoryMovement(movement) || inventoryIds.has(movement.id) || inventoryKeys.has(movement.operationKey) || !materialIds.has(movement.materialId)) return false; if (movement.purchaseId !== null && !purchaseIds.has(movement.purchaseId)) return false; if (movement.orderId !== null && !orderIds.has(movement.orderId)) return false; if (movement.type === "reversal") { if (reversedInventoryIds.has(movement.reversesMovementId)) return false; reversedInventoryIds.add(movement.reversesMovementId); } inventoryIds.add(movement.id); inventoryKeys.add(movement.operationKey); }
  for (const movement of data.inventoryMovements) { if (movement.type === "reversal") { const target = data.inventoryMovements.find((candidate) => candidate.id === movement.reversesMovementId); if (!target || target.materialId !== movement.materialId || target.quantityDeltaMilli !== -movement.quantityDeltaMilli || target.valueDeltaMinor !== -movement.valueDeltaMinor) return false; } }
  const catalogIds = new Set<string>(); const catalogKeys = new Set<string>(); const activeCatalogNames = new Set<string>();
  for (const item of data.catalogItems) { if (!validCatalogItem(item) || catalogIds.has(item.id) || catalogKeys.has(item.createdOperationKey)) return false; const key = `${item.kind}:${item.name.trim().replace(/\s+/g, " ").toLocaleLowerCase("ar-JO")}`; if (item.active && activeCatalogNames.has(key)) return false; catalogIds.add(item.id); catalogKeys.add(item.createdOperationKey); if (item.active) activeCatalogNames.add(key); }
  for (const stored of data.orders) { if (isString(stored.catalogItemId) && !catalogIds.has(stored.catalogItemId)) return false; }
  for (const draft of data.drafts) { if (isString(draft.catalogItemId) && !catalogIds.has(draft.catalogItemId)) return false; }
  const declarationIds = new Set<string>(); const declarationKeys = new Set<string>(); const reversedDeclarationIds = new Set<string>();
  for (const declaration of data.shortCashDeclarations) {
    if (!validShortCashDeclaration(declaration) || declarationIds.has(declaration.id) || declarationKeys.has(`${declaration.kind}:${declaration.idempotencyKey}`)) return false;
    declarationIds.add(declaration.id); declarationKeys.add(`${declaration.kind}:${declaration.idempotencyKey}`);
    if (declaration.kind === "reversal") { if (reversedDeclarationIds.has(declaration.reversalOfId)) return false; reversedDeclarationIds.add(declaration.reversalOfId); }
  }
  for (const declaration of data.shortCashDeclarations) {
    if (declaration.kind === "reversal") { const original = data.shortCashDeclarations.find(candidate => candidate.id === declaration.reversalOfId); if (!original || original.kind !== "declaration" || original.amountMinor !== declaration.amountMinor || original.direction !== declaration.direction || original.relatedOrderId !== declaration.relatedOrderId || original.relatedEventId !== declaration.relatedEventId) return false; }
  }
  return true;
}

function summary(file: LocalExportFile): TransferSummary {
  const snapshots = file.data.drafts.reduce((count, draft) => count + draft.costSnapshots.length, 0) + file.data.orders.reduce((count, stored) => count + stored.order.costSnapshots.length, 0);
  const events = file.data.orders.reduce((count, stored) => count + stored.order.events.length, 0);
  return { profile: file.data.profile !== null, preferences: file.data.preferences !== null, drafts: file.data.drafts.length, orders: file.data.orders.length, schedules: file.data.schedules.length, recurrences: file.data.recurrences?.length ?? 0, financialEvents: file.data.financialEvents.length, supplierPurchases: file.data.supplierPurchases?.length ?? 0, cashWallets: file.data.cashWallets?.length ?? 0, cashContinuityEntries: file.data.cashContinuityEntries?.length ?? 0, materials: file.data.materials?.length ?? 0, inventoryMovements: file.data.inventoryMovements?.length ?? 0, catalogItems: file.data.catalogItems?.length ?? 0, shortCashDeclarations: file.data.shortCashDeclarations?.length ?? 0, snapshots, events, exportedAt: file.exportedAt };
}

export class LocalTransferService {
  constructor(private readonly store: PrototypeLocalStore, private readonly now: () => string = () => new Date().toISOString()) {}

  async createExport(): Promise<TransferResult<LocalExportFile>> {
    const snapshot = await this.store.readSnapshot();
    if (!snapshot.ok) return { ok: false, code: "storage_error", message: "تعذر قراءة البيانات المحلية للتصدير. لم يُنشأ ملف." };
    return { ok: true, value: { format: localExportFormat, version: localExportVersion, schemaVersion: localSchemaVersion, exportedAt: this.now(), data: snapshot.value } };
  }

  prepareImport(text: string): TransferResult<TransferPreview> {
    let candidate: unknown;
    try { candidate = JSON.parse(text); } catch { return fail("الملف ليس JSON صالحًا. بقيت بيانات هذا الجهاز دون تغيير."); }
    if (!isRecord(candidate) || candidate.format !== localExportFormat) return fail("هذا ليس ملف تصدير Micro المحلي. بقيت بيانات هذا الجهاز دون تغيير.");
    const isCurrent = candidate.version === localExportVersion && candidate.schemaVersion === localSchemaVersion;
    const isG3Legacy = candidate.version === 6 && candidate.schemaVersion === 14;
    const isG3CurrentLegacy = candidate.version === 7 && candidate.schemaVersion === 15;
    const isPreviousG4 = candidate.version === 9 && candidate.schemaVersion === 18;
    const isPreviousG5 = candidate.version === 10 && candidate.schemaVersion === 19;
    if (!isCurrent && !isG3Legacy && !isG3CurrentLegacy && !isPreviousG4 && !isPreviousG5) return fail("إصدار الملف غير مدعوم في هذا Prototype. بقيت بيانات هذا الجهاز دون تغيير.");
    if (!isDate(candidate.exportedAt) || !isRecord(candidate.data)) return fail("الملف ناقص أو لا يطابق بنية Micro المطلوبة. بقيت بيانات هذا الجهاز دون تغيير.");
    const raw = candidate.data;
    const migrated: LocalStoreSnapshot = {
      ...raw,
      drafts: Array.isArray(raw.drafts) ? raw.drafts.map(draft => isRecord(draft) ? { ...draft, catalogItemId: draft.catalogItemId ?? null } : draft) : [],
      orders: Array.isArray(raw.orders) ? raw.orders.map(order => isRecord(order) ? { ...order, catalogItemId: order.catalogItemId ?? null, followUpSummary: order.followUpSummary ?? null, followUpDate: order.followUpDate ?? null, followUpReason: order.followUpReason ?? null, followUpEvents: Array.isArray(order.followUpEvents) ? order.followUpEvents : [] } : order) : [],
      schedules: Array.isArray(raw.schedules) ? raw.schedules.map(schedule => isRecord(schedule) ? { ...schedule, recurrenceId: schedule.recurrenceId ?? null, recurrenceIndex: schedule.recurrenceIndex ?? null } : schedule) : [], recurrences: Array.isArray(raw.recurrences) ? raw.recurrences : [], financialEvents: Array.isArray(raw.financialEvents) ? raw.financialEvents : [], supplierPurchases: Array.isArray(raw.supplierPurchases) ? raw.supplierPurchases : [], cashWallets: Array.isArray(raw.cashWallets) ? raw.cashWallets : [], cashContinuityEntries: Array.isArray(raw.cashContinuityEntries) ? raw.cashContinuityEntries : [], materials: Array.isArray(raw.materials) ? raw.materials : [], inventoryMovements: Array.isArray(raw.inventoryMovements) ? raw.inventoryMovements : [], catalogItems: Array.isArray(raw.catalogItems) ? raw.catalogItems : [], shortCashDeclarations: Array.isArray(raw.shortCashDeclarations) ? raw.shortCashDeclarations : [],
    } as unknown as LocalStoreSnapshot;
    if (!validateSnapshot(migrated)) return fail("الملف ناقص أو لا يطابق بنية Micro المطلوبة. بقيت بيانات هذا الجهاز دون تغيير.");
    const file: LocalExportFile = { format: localExportFormat, version: localExportVersion, schemaVersion: localSchemaVersion, exportedAt: candidate.exportedAt, data: migrated };
    return { ok: true, value: { file, summary: summary(file) } };
  }

  async confirmImport(preview: TransferPreview): Promise<TransferResult<TransferSummary>> {
    const replacement = await this.store.replaceSnapshot(preview.file.data);
    if (!replacement.ok) return { ok: false, code: "storage_error", message: "تعذر استبدال البيانات المحلية. لم يتم تأكيد نجاح الاستيراد." };
    return { ok: true, value: preview.summary };
  }
}
